export const gridPics = [
  {
    label: "Corporate",
    alt: "Corporate Video Production",
    src: "/images/home-page/grid-pics/grid-pic-corporate.png",
    href: "/industries/corporate",
    width: 864,
    height: 486,
    priority: false,
  },
  {
    label: "Education",
    alt: "Education Video Production",
    src: "/images/home-page/grid-pics/grid-pic-education.png",
    href: "/industries/education",
    width: 864,
    height: 486,
    priority: false,
  },
  {
    label: "Healthcare",
    alt: "Healthcare Video Production",
    src: "/images/home-page/grid-pics/grid-pic-healthcare.png",
    href: "/industries/healthcare",
    width: 864,
    height: 486,
    priority: false,
  },
  {
    label: "Nonprofit",
    alt: "Nonprofit Video Production",
    src: "/images/home-page/grid-pics/grid-pic-nonprofit.png",
    href: "/industries/nonprofit",
    width: 864,
    height: 486,
    priority: false,
  },
];