export const videoData = [
  {
    id: 1,
    category: ["Drone"],
    client: "Missouri Baptist Blues Drone",
    thumbnail_src: "/images/video-thumbnails/drone/bluesDrone.jpg",
    src: "https://player.vimeo.com/video/339585435?h=bc28655b80&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 2,
    category: ["Corporate", "Drone"],
    client: "ARTCO RECRUITMENT",
    thumbnail_src: "/images/video-thumbnails/corporate/artCoRecruitment.png",
    src: "https://player.vimeo.com/video/901619462?h=4ab57402b0&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 3,
    category: ["Corporate", "Drone"],
    client: "MMM IN GRAND CENTER",
    thumbnail_src: "/images/video-thumbnails/corporate/mmmGrandCenter.png",
    src: "https://player.vimeo.com/video/799944146?h=7ce1e106da&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 4,
    category: ["Corporate", "Drone"],
    client: "GIRL SCOUTS OF EASTERN MISSOURI PADDLE RAISE",
    thumbnail_src: "/images/video-thumbnails/corporate/paddleRaise.png",
    src: "https://player.vimeo.com/video/796701498?h=2711ae04fb&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 5,
    category: ["Corporate"],
    client: "AGILIX FAQ",
    thumbnail_src: "/images/video-thumbnails/corporate/agilix.png",
    src: "https://player.vimeo.com/video/884615900?h=43da5e09e3&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 6,
    category: ["Corporate", "Drone"],
    client: "MITEK HOUSTON GROUNDBREAKING",
    thumbnail_src: "/images/video-thumbnails/corporate/miTekHouston.png",
    src: "https://player.vimeo.com/video/779302587?h=59cf20066f&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 7,
    category: ["Corporate"],
    client: "CLUB FITNESS SHARE TO INSPIRE",
    thumbnail_src: "/images/video-thumbnails/corporate/clubFitness.png",
    src: "https://player.vimeo.com/video/772586297?h=90fd95555a&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 8,
    category: ["Corporate"],
    client: "MUSIC AT THE INTERSECTION",
    thumbnail_src: "/images/video-thumbnails/corporate/musicIntersection.png",
    src: "https://player.vimeo.com/video/862940886?h=48731807d6&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 9,
    category: ["Corporate"],
    client: "FIVE STAR AUTO BODY RECRUITMENT",
    thumbnail_src: "/images/video-thumbnails/corporate/fiveStarAuto.png",
    src: "https://player.vimeo.com/video/755292157?h=e641dc365b&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 10,
    category: ["Corporate"],
    client: "MCCARTHY BUILDING COMPANIES SPOTLIGHT AWARD",
    thumbnail_src: "/images/video-thumbnails/corporate/spotlightSolar.png",
    src: "https://player.vimeo.com/video/942506956?h=e686314ea0&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 11,
    category: ["Education", "Drone"],
    client: "EDEN THEOLOGICAL SEMINARY RECRUITMENT",
    thumbnail_src: "/images/video-thumbnails/education/edenTheological.png",
    src: "https://player.vimeo.com/video/829943828?h=c4be815d3e&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 12,
    category: ["Education"],
    client: "Medical Aesthetics Academy Demo",
    thumbnail_src: "/images/video-thumbnails/education/medicalAesthetics.png",
    src: "https://player.vimeo.com/video/798921790?h=7d1e24dd8b&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 13,
    category: ["Education"],
    client: "MURPHY COMPANY TRAINING DEMO",
    thumbnail_src: "/images/video-thumbnails/education/educationExampleOne.png",
    src: "https://player.vimeo.com/video/823476966?h=4efdfbf093&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 14,
    category: ["Education"],
    client: "St. Louis Children's Hospital My Name Matters",
    thumbnail_src:
      "/images/video-thumbnails/education/educationExampleFour.png",
    src: "https://player.vimeo.com/video/823478141?h=2becf8c74f&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 15,
    category: ["Education"],
    client: "Washington University Founders Day",
    thumbnail_src: "/images/video-thumbnails/education/washUFoundersDay.png",
    src: "https://player.vimeo.com/video/880289545?h=3226a6bf33&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 16,
    category: ["Education"],
    client: "Johnstone Sales Demo",
    thumbnail_src: "/images/video-thumbnails/education/johnstoneDemo.png",
    src: "https://player.vimeo.com/video/802838459?h=8ee67196b0&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 17,
    category: ["Education"],
    client: "WASHINGTON UNIVERSITY OLIN BUSINESS SCHOOL BIG IDEA BOUNCE PITCH CONTEST",
    thumbnail_src: "/images/video-thumbnails/education/washUOlin.png",
    src: "https://player.vimeo.com/video/820666152?h=e4f8f6c5f6&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 18,
    category: ["Education"],
    client: "Holy Childhood of Jesus School Virtual Tour",
    thumbnail_src: "/images/video-thumbnails/education/holyChildJesus.png",
    src: "https://player.vimeo.com/video/942507318?badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  // {
  //   id: 19,
  //   category: ["Education"],
  //   client: "Indiana University School of Medicine",
  //   thumbnail_src: "/images/video-thumbnails/education/indianaSchoolMed.png",
  //   src: "https://player.vimeo.com/video/942507138?h=556e4defec&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  // },
  {
    id: 19,
    category: ["Education"],
    client: "BIOSTL INTERNSHIPS",
    thumbnail_src: "/images/video-thumbnails/education/bioSTL.jpg",
    src: "https://player.vimeo.com/video/849274086?h=843ea55285&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 20,
    category: ["Medical"],
    client: "SSM Cardinal Glennon Residency Recruitment",
    src: "https://player.vimeo.com/video/872654095?h=2fbe224539&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
    thumbnail_src: "/images/video-thumbnails/medical/ssmCardinalGlennon.png",
  },
  {
    id: 21,
    category: ["Medical"],
    client: "Washington University Emergency Medicine Residency Recruitment",
    thumbnail_src:
      "/images/video-thumbnails/medical/washUEmergencyMedicine.png",
    src: "https://player.vimeo.com/video/866533299?h=90843c1f39&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 22,
    category: ["Medical"],
    client: "Washington University Neuromuscular Medicine Fellowship Recruitment",
    src: "https://player.vimeo.com/video/900179612?h=690b0e7751&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
    thumbnail_src: "/images/video-thumbnails/medical/washUNeuromuscular.png",
  },
  {
    id: 23,
    category: ["Medical"],
    client: "Siteman Cancer Center Brain Tumor Center",
    thumbnail_src: "/images/video-thumbnails/medical/siteman.png",
    src: "https://player.vimeo.com/video/842642479?h=a33d343fee&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 24,
    category: ["Medical"],
    client: "Alton Memorial Hospital Foundation's Duck Pluckers Ball",
    thumbnail_src: "/images/video-thumbnails/medical/duckPluckers.png",
    src: "https://player.vimeo.com/video/905668122?h=44f7031f29&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 25,
    category: ["Medical"],
    client: "St Louis Children's Hospital Employee Giving",
    thumbnail_src: "/images/video-thumbnails/medical/stLouisChildrens.png",
    src: "https://player.vimeo.com/video/790947100?h=a476fa3e19&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 26,
    category: ["Medical"],
    client: "PROVIDENT BEHAVIORAL HEALTH LIVE GALA ",
    thumbnail_src: "/images/video-thumbnails/medical/pbhLivestream.jpg",
    src: "https://player.vimeo.com/video/676469724?h=86dadc6885&&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 27,
    category: ["Medical"],
    client: "Ascension Healthcare, St. Vincent",
    thumbnail_src: "/images/video-thumbnails/medical/ascension.png",
    src: "https://player.vimeo.com/video/942507749?h=5211a400f9&&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 28,
    category: ["Medical"],
    client: " SSM HEALTH INDUSTRIAL REHABILITATION CENTER",
    thumbnail_src: "/images/video-thumbnails/medical/ssmHealth.png",
    src: "https://player.vimeo.com/video/943675631?h=5cd1437083&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 29,
    category: ["Nonprofit"],
    client: "Barnes Jewish Hospital Foundation Gala Highlight Video",
    thumbnail_src: "/images/video-thumbnails/nonprofit/bjhfGala.png",
    src: "https://player.vimeo.com/video/840455005?h=8cf0180342&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 30,
    category: ["Nonprofit"],
    client: "Back to China",
    thumbnail_src: "/images/video-thumbnails/nonprofit/backToChina.png",
    src: "https://player.vimeo.com/video/942508083?h=ba57cdf21e&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 31,
    category: ["Nonprofit"],
    client: " OLLIE HINKLE HEART FOUNDATION GALA FUND-A-NEED",
    thumbnail_src: "/images/video-thumbnails/nonprofit/ollieHinkle.png",
    src: "https://player.vimeo.com/video/812985606?h=a0fe83b76b&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 32,
    category: ["Nonprofit"],
    client: "Central Institute for the Deaf Out Loud",
    thumbnail_src: "/images/video-thumbnails/nonprofit/cidOutLoud.png",
    src: "https://player.vimeo.com/video/825959288?h=46ba69e53b&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 33,
    category: ["Nonprofit"],
    client: "JOSHUA CHAMBERLAIN SOCIETY GALA FUND-A-NEED",
    thumbnail_src: "/images/video-thumbnails/nonprofit/jcsGala.png",
    src: "https://player.vimeo.com/video/838407827?h=3668c77c36&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 34,
    category: ["Nonprofit"],
    client: "USO of Missouri Holiday Block Leave",
    thumbnail_src: "/images/video-thumbnails/nonprofit/usoBlockLeave.png",
    src: "https://player.vimeo.com/video/792679501?h=8a339c0ff3&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 35,
    category: ["Nonprofit"],
    client: "CARDINAL RITTER SENIOR SERVICES GALA FUND-A-NEED",
    thumbnail_src: "/images/video-thumbnails/nonprofit/crss.png",
    src: "https://player.vimeo.com/video/700538510?h=350078ccdd&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 36,
    category: ["Nonprofit"],
    client: " CYSTIC FIBROSIS FOUNDATION GALA FUND-A-NEED",
    thumbnail_src: "/images/video-thumbnails/nonprofit/cysticFibrosisGala.png",
    src: "https://player.vimeo.com/video/884469475?h=38bff527f4&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
  {
    id: 37,
    category: ["Nonprofit"],
    client: "Kids in the Middle Mission Promo",
    thumbnail_src: "/images/video-thumbnails/nonprofit/kitmMission.png",
    src: "https://player.vimeo.com/video/862525134?h=722087be67&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  },
   {
     id: 38,
     category: ["Livestream"],
     client: "Washington Universty Spring Parents Council Livestream",
     thumbnail_src: "/images/video-thumbnails/livestream/wash-u-parents-council.png",
     src: "https://player.vimeo.com/video/814356804?h=635a2eba30&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
   },
   {
     id: 39,
     category: ["Livestream"],
     client: "Spirit of Provident Gala Livestream",
     thumbnail_src: "/images/video-thumbnails/livestream/provident-gala.png",
     src: "https://player.vimeo.com/video/676469724?h=86dadc6885&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
   },
  //  {
  //   id: 40,
  //   category: ["Education"],
  //   client:  "WASHINGTON UNIVERSITY SPRING PARENTS COUNCIL",
  //   thumbnail_src: "/images/video-thumbnails/livestream/wash-u-parents-council.png",
  //   src: "https://player.vimeo.com/video/814356804?h=635a2eba30&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=1&byline=0&portrait=0",
  //  }
];