export const videoData = [
  {
    id: 44,
    category: ["Corporate"],
    client: "Synergy Living",
    title: "Synergy Living Kirkwood Development",
    image_src: "/images/video-thumbnails/corporate/synergyLiving.png",
    src: "https://player.vimeo.com/video/1024802262?h=7af899a007&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 45,
    category: ["Corporate"],
    client: "FSI",
    title: "FSI Facilities",
    image_src: "/images/video-thumbnails/corporate/fsi.png",
    src: "https://player.vimeo.com/video/1035739098?h=7af899a007&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 32,
    category: ["Nonprofit"],
    client: "Joshua Chamberlain Society",
    title: "GALA FUND-A-NEED",
    image_src: "/images/video-thumbnails/nonprofit/joshua-chamberlain.png",
    src: "https://player.vimeo.com/video/838407827?h=3668c77c36&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 33,
    category: ["Nonprofit"],
    client: "USO of Missouri",
    title: "Holiday Block Leave",
    image_src: "/images/video-thumbnails/nonprofit/usoBlockLeave.png",
    src: "https://player.vimeo.com/video/792679501?h=8a339c0ff3&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 1,
    category: ["Drone","Medical"],
    client: "Missouri Baptist",
    title: "Blues Drone",
    image_src: "/images/video-thumbnails/drone/bluesDrone.png",
    src: "https://player.vimeo.com/video/943728497?h=2a1e0843fa&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 2,
    category: ["Corporate", "Drone"],
    client: "ARTCO",
    title: "Recruitment",
    image_src: "/images/video-thumbnails/corporate/artCoRecruitment.png",
    src: "https://player.vimeo.com/video/901619462?h=4ab57402b0&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 3,
    category: ["Corporate", "Drone"],
    client: "MMM ",
    title: "IN GRAND CENTER",
    image_src: "/images/video-thumbnails/corporate/mmmGrandCenter.png",
    src: "https://player.vimeo.com/video/799944146?h=7ce1e106da&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 4,
    category: ["Corporate", "Drone"],
    client: "Girl Scouts of Eastern Missouri",
    title: "Padde Raise",
    image_src: "/images/video-thumbnails/corporate/paddleRaise.png",
    src: "https://player.vimeo.com/video/796701498?h=2711ae04fb&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 6,
    category: ["Corporate", "Drone"],
    client: "MiTek",
    title: "Houston Groundbreaking",
    image_src: "/images/video-thumbnails/corporate/miTekHouston.png",
    src: "https://player.vimeo.com/video/779302587?h=59cf20066f&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 7,
    category: ["Corporate"],
    client: "Club Fitness",
    title: "SHARE TO INSPIRE",
    image_src: "/images/video-thumbnails/corporate/club-fitness.png",
    src: "https://player.vimeo.com/video/772586297?h=90fd95555a&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 8,
    category: ["Corporate"],
    client: "Music at the Intersection",
    title: "Highlight",
    image_src: "/images/video-thumbnails/corporate/musicIntersection.png",
    src: "https://player.vimeo.com/video/862940886?h=48731807d6&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 9,
    category: ["Corporate"],
    client: "Five Star Auto Body",
    title: "RECRUITMENT",
    image_src: "/images/video-thumbnails/corporate/fiveStarAuto.png",
    src: "https://player.vimeo.com/video/755292157?h=e641dc365b&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 11,
    category: ["Education", "Drone"],
    client: "Eden Theological Seminary",
    title: "RECRUITMENT",
    image_src: "/images/video-thumbnails/education/edenTheological.png",
    src: "https://player.vimeo.com/video/829943828?h=c4be815d3e&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 13,
    category: ["Education"],
    client: "Murphy Company",
    title: "TRAINING DEMO",
    image_src: "/images/video-thumbnails/education/educationExampleOne.png",
    src: "https://player.vimeo.com/video/823476966?h=4efdfbf093&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 15,
    category: ["Education"],
    client: "Washington University",
    title: "Founders Day",
    image_src: "/images/video-thumbnails/education/washUFoundersDay.png",
    src: "https://player.vimeo.com/video/880289545?h=3226a6bf33&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 16,
    category: ["Education"],
    client: "Johnstone Sales",
    title: "Demo",
    image_src: "/images/video-thumbnails/education/johnstoneDemo.png",
    src: "https://player.vimeo.com/video/802838459?h=8ee67196b0&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 17,
    category: ["Education"],
    client: "Washington University Olin Business School",
    title: "Big Idea Bounce Contest",
    image_src: "/images/video-thumbnails/education/washUOlin.jpg",
    src: "https://player.vimeo.com/video/820666152?h=e4f8f6c5f6&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 19,
    category: ["Education"],
    client: "BioSTL",
    title: "Internships",
    image_src: "/images/video-thumbnails/education/bioSTL.jpg",
    src: "https://player.vimeo.com/video/849274086?h=843ea55285&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 20,
    category: ["Medical"],
    client: "SSM Cardinal Glennon",
    title: "Residency Recruitment",
    src: "https://player.vimeo.com/video/872654095?h=2fbe224539&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    image_src: "/images/video-thumbnails/medical/ssmCardinalGlennon.png",
  },
  {
    id: 21,
    category: ["Medical"],
    client: "Washington University Emergency Medicine",
    title: "Residency Recruitment",
    image_src: "/images/video-thumbnails/medical/washUEmergencyMedicine.png",
    src: "https://player.vimeo.com/video/866533299?h=90843c1f39&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 22,
    category: ["Medical"],
    client: "Washington University Neuromuscular Medicine",
    title: "Fellowship Recruitment",
    src: "https://player.vimeo.com/video/900179612?h=690b0e7751&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    image_src: "/images/video-thumbnails/medical/washUNeuromuscular.png",
  },
  {
    id: 23,
    category: ["Medical"],
    client: "Siteman Cancer Center",
    title: "Brain Tumor Center",
    image_src: "/images/video-thumbnails/medical/siteman.png",
    src: "https://player.vimeo.com/video/842642479?h=a33d343fee&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 24,
    category: ["Medical"],
    client: "Alton Memorial Hospital Foundation",
    title: "Duck Pluckers Ball",
    image_src: "/images/video-thumbnails/medical/duckPluckers.png",
    src: "https://player.vimeo.com/video/905668122?h=44f7031f29&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 25,
    category: ["Medical"],
    client: "St Louis Children's Hospital",
    title: "Employee Giving",
    image_src: "/images/video-thumbnails/medical/stLouisChildrens.png",
    src: "https://player.vimeo.com/video/790947100?h=a476fa3e19&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 26,
    category: ["Medical"],
    client: "Ascension Healthcare",
    title: "St. Vincent",
    image_src: "/images/video-thumbnails/medical/ascension.png",
    src: "https://player.vimeo.com/video/942507749?h=5211a400f9&&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 27,
    category: ["Medical"],
    client: "SSM Health",
    title: "Industrial Rehabilitaion Center",
    image_src: "/images/video-thumbnails/medical/ssmHealth.png",
    src: "https://player.vimeo.com/video/943675631?h=5cd1437083&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 28,
    category: ["Nonprofit"],
    client: "Barnes-Jewish Hospital Foundation",
    title: "Illumination Gala",
    image_src: "/images/video-thumbnails/nonprofit/bjhfGala.png",
    src: "https://player.vimeo.com/video/840455005?h=8cf0180342&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 30,
    category: ["Nonprofit"],
    client: " Ollie Hinkle Heart Foundation",
    title: "Gala Fund-A-Need",
    image_src: "/images/video-thumbnails/nonprofit/ollie-hinkle.png",
    src: "https://player.vimeo.com/video/812985606?h=a0fe83b76b&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 31,
    category: ["Nonprofit"],
    client: "Central Institute for the Deaf",
    title: "Out Loud",
    image_src: "/images/video-thumbnails/nonprofit/cidOutLoud.png",
    src: "https://player.vimeo.com/video/825959288?h=46ba69e53b&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 34,
    category: ["Nonprofit"],
    client: "Cardinal Ritter Senior Services",
    title: "Gala Fund-A-Need",
    image_src: "/images/video-thumbnails/nonprofit/crss.png",
    src: "https://player.vimeo.com/video/700538510?h=350078ccdd&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 35,
    category: ["Nonprofit"],
    client: "Cystic Fibrosis Foundation",
    title: "Gala Fund-A-Need",
    image_src: "/images/video-thumbnails/nonprofit/cysticFibrosisGala.png",
    src: "https://player.vimeo.com/video/884469475?h=38bff527f4&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 36,
    category: ["Nonprofit"],
    client: "Kids in the Middle",
    title: "Mission Promo",
    image_src: "/images/video-thumbnails/nonprofit/kitmMission.png",
    src: "https://player.vimeo.com/video/862525134?h=722087be67&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 39,
    category: ["Livestream"],
    client: "Spirit of Provident",
    title: "Gala Livestream",
    image_src: "/images/video-thumbnails/livestream/provident-gala.png",
    src: "https://player.vimeo.com/video/676469724?h=86dadc6885&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 40,
    category: ["Animation","Medical"],
    client: "St. Louis Children's Hospital",
    title: "What to Expect - Colonoscopy",
    image_src: "/images/video-thumbnails/animation/animation-example.png",
    src: "https://player.vimeo.com/video/823498854?h=49fb6c4ebf&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 41,
    category: ["Animation","Education"],
    client: "Washington University",
    title: "Always Olin",
    image_src: "/images/video-thumbnails/animation/always-olin.png",
    src: "https://player.vimeo.com/video/944136129?h=701f2488bb&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    id: 42,
    category: ["Animation","Education"],
    client: "Washington University",
    title: "Olin MBA",
    image_src: "/images/video-thumbnails/animation/olin-mba.png",
    src: "https://player.vimeo.com/video/823498955?h=815218068d&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  // {
  //   id: 43,
  //   category: ["Animation","Education"],
  //   client: "Washington University",
  //   title: "Big Idea Bounce",
  //   image_src: "/images/video-thumbnails/animation/big-idea-bounce.png",
  //   src: "https://player.vimeo.com/video/930759771?h=7af899a007&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  // },
  // {
  //   id: 46,
  //   category: ["Corporate"],
  //   client: "Club Fitness",
  //   title: "15 Second Promo",
  //   image_src: "",
  //   src: "https://player.vimeo.com/video/1042932679?h=8032012bdc&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  // },
  // {
  //   id: 47,
  //   category: ["Corporate", "Drone"],
  //   client: "McCarthy Building Companies",
  //   title: "Project Spotlight",
  //   image_src: "",
  //   src: "https://player.vimeo.com/video/1004659940?h=83dc5242f5&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  // },
  // {
  //   id: 48,
  //   category: ["Medical"],
  //   client: "St. Louis Children's Hospital Foundation",
  //   title: "CMN Patient Ambassadors",
  //   image_src: "",
  //   src: "https://player.vimeo.com/video/930793149?h=2a6f6a2764&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  // },
  // {
  //   id: 49,
  //   category: ["Education"],
  //   client: "The Marianists",
  //   title: "Marianist DIL",
  //   image_src: "",
  //   src: "https://player.vimeo.com/video/942118194?h=c9ee03bedc&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  // },
  // {
  //   category: [],
  //   client: "",
  //   title: "",
  //   image_src: "",
  //   src: "",
  // },
  // {
  //   id: 5,
  //   category: ["Corporate"],
  //   client: "AGILIX",
  //   title: "FAQ",
  //   image_src: "/images/video-thumbnails/corporate/agilix.png",
  //   src: "https://player.vimeo.com/video/884615900?h=43da5e09e3&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  // },
  // {
  //   id: 10,
  //   category: ["Corporate"],
  //   client: "MCCARTHY BUILDING COMPANIES",
  //   title: "SPOTLIGHT AWARD",
  //   image_src: "/images/video-thumbnails/corporate/spotlightSolar.png",
  //   src: "https://player.vimeo.com/video/942506956?h=e686314ea0&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  // },
  // {
  //   id: 12,
  //   category: ["Education"],
  //   client: "Medical Aesthetics Academy",
  //   title: "Demo",
  //   image_src: "/images/video-thumbnails/education/medicalAesthetics.png",
  //   src: "https://player.vimeo.com/video/798921790?h=7d1e24dd8b&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  // },
  // {
  //   id: 14,
  //   category: ["Education"],
  //   client: "St. Louis Children's Hospital",
  //   title: "My Name Matters",
  //   image_src: "/images/video-thumbnails/education/educationExampleFour.png",
  //   src: "https://player.vimeo.com/video/823478141?h=2becf8c74f&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  // },
  // {
  //   id: 18,
  //   category: ["Education"],
  //   client: "Holy Childhood of Jesus School",
  //   title: "Virtual Tour",
  //   image_src: "/images/video-thumbnails/education/holyChildJesus.png",
  //   src: "https://player.vimeo.com/video/942507318?badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  // },
  // {
  //   id: 29,
  //   category: ["Nonprofit"],
  //   client: "Back to China",
  //   title: "",
  //   image_src: "/images/video-thumbnails/nonprofit/backToChina.png",
  //   src: "https://player.vimeo.com/video/942508083?h=ba57cdf21e&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  // },
  // {
  //   id: 37,
  //   category: ["Education"],
  //   client: "Washington Universty",
  //   title: "Spring Parents Council Livestream",
  //   image_src: "/images/video-thumbnails/education/springParentsCouncil.jpg",
  //   alt_image_src:
  //     "/images/video-thumbnails/livestream/wash-u-parents-council.png",
  //   src: "https://player.vimeo.com/video/814356804?h=635a2eba30&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  // },
  // {
  //   id: 38,
  //   category: ["Livestream"],
  //   client: "Washington Universty",
  //   title: "Spring Parents Council Livestream",
  //   image_src:"/images/video-thumbnails/livestream/wash-u-parents-council.png",
  //   src: "https://player.vimeo.com/video/814356804?h=635a2eba30&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  // },
];
