export const workSampleData = [
  {
    category: ["Corporate", "Video Editing", "Video Production", "Drone"],
    client: "Synergy Living",
    description:
      "Aerial footage and promotional video for Kirkwood development. Produced by Mike Martin Media for Synergy Living.",
    title: "Synergy Living Kirkwood Development",
    image_src: "/images/work-gallery-cover-images/synergy-living-cover.jpg",
    featured: "featured-drone",
    slug: "synergy-living-kirkwood-development",
    playback_id: "Ew5m01K6MN8Cll4omLFDCIrxfygsA01FlW6VNLCSQvf5E",
  },
  {
    category: ["Corporate", "Video Editing", "Video Production", "Animation"],
    client: "FSI",
    description:
      "Promotional video showcasing FSI's facilities. Produced by Mike Martin Media for FSI.",
    title: "FSI Facilities",
    image_src: "/images/work-gallery-cover-images/fsi-cover.jpg",
    featured: "",
    slug: "fsi-facilities",
    playback_id: "n3lJ3gR0065nqp76IVFOMwfeg4FlGou9QKULCHoe6011s",
  },
  {
    category: ["Nonprofit", "Video Editing", "Video Production"],
    client: "Joshua Chamberlain Society",
    description:
      "Promotional video for the Joshua Chamberlain Society. Produced by Mike Martin Media.",
    title: "Joshua Chamberlain Society",
    image_src: "/images/work-gallery-cover-images/jcs-cover.jpg",
    featured: "featured-video-production",
    slug: "joshua-chamberlain-society",
    playback_id: "BH5LJ023ms4BhtIMsTbYR8NBFyvIfGuYi02CYK01CcQXPY",
  },
  {
    category: ["Nonprofit", "Video Editing", "Video Production"],
    client: "USO of Missouri",
    description:
      "Promotional video for the USO of Missouri's Holiday Block Leave event. Produced by Mike Martin Media.",
    title: "Holiday Block Leave",
    image_src: "/images/work-gallery-cover-images/uso-of-mo-cover.jpg",
    featured: "featured-video-editing",
    slug: "uso-holiday-block-leave",
    playback_id: "QWSGoozIfg3C6sDNwq00uPCsPJkiMykaPOKNBOEfuIqQ",
  },
  {
    category: ["Corporate", "Drone", "Video Editing", "Video Production"],
    client: "ARTCO",
    description:
      "Promotional video for ARTCO's recruitment efforts. Produced by Mike Martin Media.",
    title: "Recruitment",
    image_src: "/images/work-gallery-cover-images/artco-cover.jpg",
    featured: "featured-drone",
    slug: "artco-recruitment",
    playback_id: "i02vEUY6w0200L8fUwlMCgrHim7aMX9jZ28KUVREmQ00ux00",
  },
  {
    category: ["Corporate", "Drone", "Video Editing", "Video Production"],
    client: "MMM",
    description:
      "Video showcasing the Grand Center Arts District in the Heart of Midtown St. Louis where the Mike Martin Media studio is located. Produced by Mike Martin Media for MMM.",
    title: "MMM In Grand Center",
    image_src: "/images/work-gallery-cover-images/mmm-cover.jpg",
    featured: "featured-video-editing",
    slug: "mmm-grand-center",
    playback_id: "gZqH26tHMzJpLOtFYSYTvNPKS7Mc1ZkP02KfCgah8hgY",
  },
  {
    category: ["Corporate", "Drone", "Video Editing", "Video Production"],
    client: "Girl Scouts of Eastern Missouri",
    description:
      "Promotional video for the Girl Scouts of Eastern Missouri's Paddle Raise event. Produced by Mike Martin Media.",
    title: "Paddle Raise",
    image_src: "/images/work-gallery-cover-images/gsem-cover.jpg",
    featured: "featured-drone",
    slug: "girl-scouts-paddle-raise",
    playback_id: "9xQ02dyt018stVTqRWZtLxvTKK6ixmcZsJ2Ll5EBJxcxk",
  },
  {
    category: ["Corporate", "Video Editing", "Video Production"],
    client: "MiTek",
    description:
      "Promotional video for MiTek's Houston Groundbreaking event. Produced by Mike Martin Media for MiTek.",
    title: "Houston Groundbreaking",
    image_src: "/images/work-gallery-cover-images/mitek-cover.jpg",
    featured: "featured-video-editing",
    slug: "mitek-houston-groundbreaking",
    playback_id: "6CimxoElh8LuHWW01DTnRVnFwGzyIxKb1fsYhtMr6jMo",
  },
  {
    category: ["Corporate", "Video Editing", "Video Production"],
    client: "Club Fitness",
    description:
      "Video for Club Fitness's Share to Inspire campaign. Produced by Mike Martin Media for Club Fitness.",
    title: "Share to Inspire",
    image_src: "/images/work-gallery-cover-images/club-fitness-share-cover.jpg",
    featured: "featured-video-production",
    slug: "club-fitness-share-to-inspire",
    playback_id: "9vgQRJYMuFs6P00PnWWJ9Q2L1D9EfBs1lGdp1fpFGHaw",
  },
  {
    category: ["Corporate", "Video Editing", "Video Production", "Drone"],
    client: "Music at the Intersection",
    description:
      "Highlight video for the Music at the Intersection festival. Produced by Mike Martin Media.",
    title: "Highlights",
    image_src: "/images/work-gallery-cover-images/mati-cover.jpg",
    featured: "featured-drone",
    slug: "music-at-the-intersection-highlight",
    playback_id: "HyzjRoAz4OWPsYhG3K5c47xrTDu00hu301JYKTFRlg8cM",
  },
  {
    category: ["Corporate", "Video Editing", "Video Production", "Drone"],
    client: "Five Star Auto Body",
    description:
      "Recruitment video for Five Star Auto Body. Produced by Mike Martin Media for Five Star Auto Body.",
    title: "Recruitment",
    image_src: "/images/work-gallery-cover-images/five-star-auto-cover.jpg",
    featured: "featured-video-production",
    slug: "five-star-auto-body",
    playback_id: "juBrOCDRJx77CMHfjvYItPp7QknxO7DYPMmpw9rECGU",
  },
  {
    category: ["Education", "Drone", "Video Editing", "Video Production"],
    client: "Eden Theological Seminary",
    description:
      "Recruitment video for Eden Theological Seminary. Produced by Mike Martin Media.",
    title: "Recruitment",
    image_src: "/images/work-gallery-cover-images/eden-theological-cover.jpg",
    featured: "",
    slug: "eden-theological-seminary",
    playback_id: "xwUzi5hOBtqb3kBbOUR3J34vpqWRM00rQLlvr6Eiih5o",
  },
  {
    category: ["Education", "Video Editing", "Video Production"],
    client: "Murphy Company",
    description:
      "Training video for Murphy Company. Produced by Mike Martin Media.",
    title: "Training Demo",
    image_src: "/images/work-gallery-cover-images/murphy-company-cover.jpg",
    featured: "",
    slug: "murphy-company-training-demo",
    playback_id: "6Fc011Miq4aZlH5lMbG9DOh9KIfENA5lLFZDdGalefks",
  },
  {
    category: ["Education", "Video Editing", "Video Production"],
    client: "Washington University",
    description:
      "Promotional video for Washington University's Founders Day event. Produced by Mike Martin Media for Washington University in St. Louis, Missouri.",
    title: "Founders Day",
    image_src: "/images/work-gallery-cover-images/wash-u-cover.jpg",
    featured: "featured-video-production",
    slug: "washington-university-founders-day",
    playback_id: "RSiMuGkyI12xEAoojkRxZ5zGZNTA8l2iVaMV02DERVJc",
  },
  {
    category: ["Education", "Video Editing", "Video Production"],
    client: "Johnstone Sales",
    description:
      "Demo video for Johnstone Sales. Produced by Mike Martin Media.",
    title: "Demo",
    image_src: "/images/work-gallery-cover-images/johnston-sales-cover.jpg",
    featured: "",
    slug: "johnstone-sales-demo",
    playback_id: "01u02ZAdlHQdqCLER01oRDjl94siohYStZQKOHbqXstf6Y",
  },
  {
    category: ["Education", "Video Editing", "Video Production"],
    client: "Washington University Olin Business School",
    description:
      "Promotional video for the Big Idea Bounce Contest at Washington University Olin Business School in St. Louis, Missouri. Produced by Mike Martin Media.",
    title: "Big Idea Bounce Contest",
    image_src: "/images/work-gallery-cover-images/wash-u-olin-cover.jpg",
    featured: "",
    slug: "washington-university-olin-business-school",
    playback_id: "YYQ6UanPhC00H4yBQEh1HIZRr9VCqV4dhod5D2Hwk52Y",
  },
  {
    category: ["Education", "Video Editing", "Video Production"],
    client: "BioSTL",
    description:
      "Promotional video for BioSTL's Internships program. Produced by Mike Martin Media.",
    title: "Internships",
    image_src: "/images/work-gallery-cover-images/bio-stl-cover.jpg",
    featured: "featured-video-production",
    slug: "biostl-internships",
    playback_id: "wPS023RyFR02Fi1ZJcGBUByvMHmPm9fGby00JZ3KhALAsY",
  },
  {
    category: ["Medical", "Video Editing", "Video Production"],
    client: "SSM Cardinal Glennon",
    description:
      "Recruitment video for SSM Cardinal Glennon's Residency program. Produced by Mike Martin Media.",
    title: "Residency Recruitment",
    image_src:
      "/images/work-gallery-cover-images/ssm-cardinal-glennon-cover.jpg",
    featured: "featured-video-editing",
    slug: "ssm-cardinal-glennon-residency-recruitment",
    playback_id: "DmRMOtlrCXCRRcNSaohUTsjKRpFV2tMG00dOQ02qgKPV4",
  },
  {
    category: ["Medical", "Video Editing", "Video Production", "Drone"],
    client: "Washington University Emergency Medicine",
    description:
      "Recruitment video for Washington University Emergency Medicine's Residency program. Produced by Mike Martin Media.",
    title: "Residency Recruitment",
    image_src:
      "/images/work-gallery-cover-images/wash-u-emergency-med-cover.jpg",
    featured: "",
    slug: "washington-university-emergency-medicine-residency-recruitment",
    playback_id: "Kgk5Q5a02D500UlTMRCQEU8kIOFfvoCHTC8woh1cx2usg",
  },
  {
    category: ["Medical", "Video Editing", "Video Production", "Drone"],
    client: "Washington University Neuromuscular Medicine",
    description:
      "Recruitment video for Washington University Neuromuscular Medicine's Fellowship program. Produced by Mike Martin Media.",
    title: "Fellowship Recruitment",
    image_src: "/images/work-gallery-cover-images/wash-u-nm-med-cover.jpg",
    featured: "featured-video-editing",
    slug: "washington-university-neuromuscular-medicine-fellowship-recruitment",
    playback_id: "e83BWhlxeVgU9wwhDLIwmUGEH9edNffmxRTkb8xMK3U",
  },
  {
    category: ["Medical", "Video Editing", "Video Production", "Drone"],
    client: "Siteman Cancer Center",
    description:
      "Promotional video for Siteman Cancer Center's Brain Tumor Center. Produced by Mike Martin Media.",
    title: "Brain Tumor Center",
    image_src: "/images/work-gallery-cover-images/siteman-cover.jpg",
    featured: "",
    slug: "siteman-cancer-center-brain-tumor-center",
    playback_id: "MpQfcdoSpfsPHabAEwaLb5heldy1FtWrOdJQdcaum9A",
  },
  {
    category: ["Medical", "Video Editing", "Video Production"],
    client: "Alton Memorial Hospital Foundation",
    description:
      "Promotional video for Alton Memorial Hospital Foundation's Duck Pluckers Ball event. Produced by Mike Martin Media.",
    title: "Duck Pluckers Ball",
    image_src: "/images/work-gallery-cover-images/alton-memorial-cover.png",
    featured: "",
    slug: "alton-memorial-hospital-foundation-duck-pluckers-ball",
    playback_id: "fA1KSlhGo7x635ShSJ78Y024yOEx01LnhhgtOhMM01xNFM",
  },
  {
    category: ["Medical", "Video Editing", "Video Production", "Drone"],
    client: "St Louis Children's Hospital",
    description:
      "Promotional video for St. Louis Children's Hospital's Employee Giving program. Produced by Mike Martin Media.",
    title: "Employee Giving",
    image_src: "/images/work-gallery-cover-images/childrens-hospital-cover.jpg",
    featured: "",
    slug: "st-louis-childrens-hospital-employee-giving",
    playback_id: "SfPpIVJeQyv2hwRLKSBNmdWWK23KxmFFPPAHNdUTpNI",
  },
  {
    category: ["Medical", "Video Editing", "Video Production", "Drone"],
    client: "Ascension Healthcare",
    description:
      "Promotional video for Ascension Healthcare St. Vincent's new facility. Produced by Mike Martin Media.",
    title: "St. Vincent Hospital",
    image_src: "/images/work-gallery-cover-images/ascension-cover.jpg",
    featured: "featured-drone",
    slug: "ascension-healthcare-st-vincent",
    playback_id: "sUAjp9VonRz0200PST5pdU8slYTUdUAOsSa01jeyW3seHs",
  },
  {
    category: ["Medical", "Video Editing", "Video Production"],
    client: "SSM Health",
    description:
      "Promotional video for SSM Health's Industrial Rehabilitation Center. Produced by Mike Martin Media.",
    title: "Industrial Rehabilitation Center",
    image_src: "/images/work-gallery-cover-images/ssm-health-cover.jpg",
    featured: "",
    slug: "ssm-health-industrial-rehabilitation-center",
    playback_id: "vUuwUh4015AuKPQ2MVIAIqZdI2gCCI7K8ZuwLMB5Q0002s",
  },
  {
    category: ["Nonprofit", "Video Editing", "Video Production"],
    client: "Barnes-Jewish Hospital Foundation",
    description:
      "Promotional video for Barnes-Jewish Hospital Foundation's Illumination Gala. Produced by Mike Martin Media.",
    title: "Illumination Gala",
    image_src: "/images/work-gallery-cover-images/bjaf-gala-cover.jpg",
    featured: "",
    slug: "barnes-jewish-hospital-foundation-illumination-gala",
    playback_id: "00QesX01y4dF6w5jVj9NuOmj4M2euvLFky2ZvHQQiRsYk",
  },
  {
    category: ["Nonprofit", "Video Editing", "Video Production"],
    client: "Ollie Hinkle Heart Foundation",
    description:
      "Promotional video for the Ollie Hinkle Heart Foundation. Produced by Mike Martin Media.",
    title: "Ollie Hinkle Heart Foundation",
    image_src: "/images/work-gallery-cover-images/ollie-hinkle-cover.jpg",
    featured: "featured-video-production",
    slug: "ollie-hinkle-heart-foundation",
    playback_id: "s01s3jW6LygKI00Eihn01Botr14al1x7Nbl8RbWVNrSX74",
  },
  {
    category: ["Nonprofit", "Video Editing", "Video Production"],
    client: "Central Institute for the Deaf",
    description:
      "An inspirational video from the Central Institute for the Deaf. Produced by Mike Martin Media.",
    title: "CID Out Loud",
    image_src: "/images/work-gallery-cover-images/cid-cover.jpg",
    featured: "",
    slug: "central-institute-for-the-deaf-out-loud",
    playback_id: "LIBn8IVDyJGpck2MwlnKmfd1X6sCexMlObFCNk02v3500",
  },
  {
    category: ["Nonprofit", "Video Editing", "Video Production"],
    client: "Cardinal Ritter Senior Services",
    description:
      "Promotional video for Cardinal Ritter Senior Services'. Produced by Mike Martin Media.",
    title: "Cardinal Ritter Senior Services",
    image_src: "/images/work-gallery-cover-images/cardinal-ritter-cover.jpg",
    featured: "",
    slug: "cardinal-ritter-senior-services-gala",
    playback_id: "znHYbB28yCxf01TTQeH01LEs92jjoD9j00ZtlqVVehT3wY",
  },
  {
    category: ["Nonprofit", "Video Editing", "Video Production"],
    client: "Cystic Fibrosis Foundation",
    description:
      "Promotional video for the Cystic Fibrosis Foundation. Produced by Mike Martin Media.",
    title: "Cystic Fibrosis Foundation",
    image_src: "/images/work-gallery-cover-images/cystic-fibrosis-cover.jpg",
    featured: "",
    slug: "cystic-fibrosis-foundation-gala",
    playback_id: "TNWjVZZJA02tzoPLSrdm2cF01VqIOUTYVexN8PDAYH6L4",
  },
  {
    category: ["Nonprofit", "Video Editing", "Video Production"],
    client: "Kids in the Middle",
    description:
      "Promotional video for Kids in the Middle's mission and services. Produced by Mike Martin Media.",
    title: "Mission Promo",
    image_src: "/images/work-gallery-cover-images/kitm-cover.jpg",
    featured: "",
    slug: "kids-in-the-middle-mission-promo",
    playback_id: "Y00ZE0075b201oINZ2FMNFXw3OJ8qbGjyLGvEYj66UbN2o",
  },
  {
    category: ["Nonprofit", "Livestream", "Video Editing", "Video Production"],
    client: "Spirit of Provident",
    description:
      "Livestream video for Spirit of Provident's Gala. Produced live by Mike Martin Media.",
    title: "Gala Livestream",
    image_src:
      "/images/work-gallery-cover-images/provident-livestream-cover.jpg",
    featured: "",
    slug: "spirit-of-provident-gala-livestream",
    playback_id: "oEHOs3PnC6SWe1q02rRklAPA02VUXss01rtI9dbRgIFSlM",
  },
  {
    category: ["Animation", "Medical", "Video Editing", "Video Production"],
    client: "St. Louis Children's Hospital",
    description:
      "Animated video for St. Louis Children's Hospital explaining what to expect during a colonoscopy procedure. Produced by Mike Martin Media.",
    title: "What to Expect - Colonoscopy",
    image_src:
      "/images/work-gallery-cover-images/childrens-hospital-animation-cover.jpg",
    featured: "",
    slug: "st-louis-childrens-hospital-what-to-expect-colonoscopy",
    playback_id: "F7LitfgebvYabDtZzRfsKp8COrekS7MRX8hOsAblWII",
  },
  {
    category: ["Animation", "Education", "Video Editing", "Video Production"],
    client: "Washington University",
    description:
      "Animated video for Washington University's Olin Business School. Produced by Mike Martin Media.",
    title: "Always Olin",
    image_src: "/images/work-gallery-cover-images/wash-u-animation-cover.jpg",
    featured: "",
    slug: "washington-university-always-olin",
    playback_id: "K009cQxd5JEwcydxMDc2LydCR5g02ukmBEEAAT7iloupU",
  },
  {
    category: ["Animation", "Education", "Video Editing", "Video Production"],
    client: "Washington University",
    description:
      "Animated video for Washington University's Olin Business School. Produced by Mike Martin Media.",
    title: "Olin MBA Digital Impact Project",
    image_src:
      "/images/work-gallery-cover-images/wash-u-olin-business-animation-cover.jpg",
    featured: "",
    slug: "washington-university-olin-mba",
    playback_id: "ARxRfC3qvYWEcjMA01WvkBT4jVAzn9xQsnJXebMOed2Y",
  },
  {
    category: ["Corporate", "Video Editing", "Video Production"],
    client: "Club Fitness",
    description:
      "Promotional video for Club Fitness. Produced by Mike Martin Media.",
    title: "15 Second Promo",
    image_src: "/images/work-gallery-cover-images/club-fitness-promo-cover.jpg",
    featured: "",
    slug: "club-fitness-15-second-promo",
    playback_id: "Oi00BwI5FLvUcFFkKbTAAZjmgVDmkt8kW4LHBBQsJOjg",
  },
  {
    category: ["Corporate", "Video Editing", "Video Production", "Drone"],
    client: "McCarthy Building Companies",
    description:
      "Promotional video for McCarthy Building Companies. Produced by Mike Martin Media.",
    title: "Project Spotlight",
    image_src: "/images/work-gallery-cover-images/mccarthy-cover.jpg",
    featured: "featured-drone",
    slug: "mccarthy-building-companies-project-spotlight",
    playback_id: "vGh5zV8aa01xCXjoJFEW8ZmNx01fbpJTSjKiBxM02olsZg",
  },
  {
    category: ["Medical", "Video Editing", "Video Production"],
    client: "St. Louis Children's Hospital Foundation",
    description:
      "Promotional video for St. Louis Children's Hospital Foundation. Produced by Mike Martin Media.",
    title: "CMN Patient Ambassadors",
    image_src:
      "/images/work-gallery-cover-images/stlouis-childrens-hospital-foundation-cover.jpg",
    featured: "featured-video-editing",
    slug: "st-louis-childrens-hospital-foundation",
    playback_id: "4pewLDrQP8GhBt02y00jMtvNlAoODOKrrYE01ABS1TEOoQ",
  },
  {
    category: ["Education", "Video Editing", "Video Production"],
    client: "The Marianists",
    description:
      "Promotional video for The Marianists DIL program. Produced by Mike Martin Media.",
    title: "Marianist DIL",
    image_src: "/images/work-gallery-cover-images/marianists-cover.jpg",
    featured: "",
    slug: "the-marianists-dil",
    playback_id: "CjQAA9M6755IcsDkW84UsTL3EVo7Uz01XKwCCNiT7hfU",
  },
  {
    category: ["Education", "Livestream", "Video Editing", "Video Production"],
    client: "Sam Fox School",
    description:
      "Livestream video for the Sam Fox School Awards of Distinction 2023. Produced live by Mike Martin Media.",
    title: "Sam Fox School Awards of Distinction 2023",
    image_src: "/images/work-gallery-cover-images/sam-fox-school-cover.jpg",
    featured: "",
    slug: "sam-fox-school-awards-of-distinction-2023",
    playback_id: "5YrtZaS2cxlVXzzK5svS49PyeL01tUnDv11c3dmLOuC4",
  },
  {
    category: ["Video Editing", "Video Production"],
    client: "Central Institute for the Deaf",
    description:
      "Inspirational video from the Central Institute for the Deaf. Produced by Mike Martin Media.",
    title: "CID Out Loud - Wyatt's Story",
    image_src: "/images/work-gallery-cover-images/cid-outloud-cover.jpg",
    featured: "",
    slug: "cid-out-loud",
    playback_id: "Bval02scaL1XiLE6AFKNcgZvN9qLZPfDHcCAD02MZFsA8",
  },
  {
    category: ["Video Editing", "Video Production"],
    client: "Evertrue",
    description:
      "Promotional video for highlighting social opportunities at Evertrue's Illinois facility. Produced by Mike Martin Media.",
    title: "Social Opportunities at Evertrue - Illinois",
    image_src: "/images/work-gallery-cover-images/evertrue-cover.jpg",
    featured: "",
    slug: "evertrue-social-opportunities",
    playback_id: "3Kt3bRKuoXCImNBvTslgsgnhnM02X2HB4GgFghb01JwHs",
  },
  {
    category: ["Corporate", "Animation", "Video Editing", "Video Production"],
    client: "Midland Wood Products",
    description:
      "Animated promotional video for Midland Wood Products. Produced by Mike Martin Media.",
    title: "Midland Wood Products",
    image_src:
      "/images/work-gallery-cover-images/midland-wood-products-cover.webp",
    featured: "",
    slug: "midland-wood-products",
    playback_id: "rAK91DoZ8Gat9ZB01LHwPhF3rrzz2Fir00cZHx95xs7J4",
  },
  {
    category: ["Corporate", "Animation", "Video Editing", "Video Production"],
    client: "MiTek Ecosystem",
    description:
      "Animated promotional video for MiTek Ecosystem. Produced by Mike Martin Media.",
    title: "MiTek Ecosystem",
    image_src: "/images/work-gallery-cover-images/mitek-ecosystem-cover.webp",
    featured: "",
    slug: "mitek-ecosystem",
    playback_id: "6nvLNWtEeccNPGKUhm4Apz0200nbEpqQ02Upl01kd5jc3Lw",
  },
  {
    category: ["Photography", "Nonprofit"],
    client: "Catholic Charities of St. Louis",
    description: "Employee photo gallery for Catholic Charities of St. Louis.",
    title: "Catholic Charities of St. Louis Photo Gallery",
    image_src:
      "/images/work-gallery-cover-images/photography/catholic-charities-gallery-cover.png",
    featured: "featured-photography",
    slug: "catholic-charities-of-st-louis-photo-gallery",
  },
  {
    category: ["Photography", "Corporate"],
    client: "Prasino",
    description: "Photo gallery for Prasino restaurant.",
    title: "Prasino Photo Gallery",
    image_src:
      "/images/work-gallery-cover-images/photography/prasino-gallery-cover.png",
    featured: "featured-photography",
    slug: "prasino-photo-gallery",
  },
  {
    category: ["Photography", "Corporate"],
    client: "Club Fitness",
    description: "Photo gallery for a Club Fitness employee event.",
    title: "Club Fitness Photo Gallery",
    image_src:
      "/images/work-gallery-cover-images/photography/club-fitness-gallery-cover.png",
    featured: "featured-photography",
    slug: "club-fitness-photo-gallery",
  },
  {
    category: ["Photography", "Corporate"],
    client: "Belden",
    description: "Photo gallery for Belden products.",
    title: "Belden Photo Gallery",
    image_src: "/images/work-gallery-cover-images/photography/belden.png",
    featured: "featured-photography",
    slug: "belden-photo-gallery",
  },
  {
    category: ["Photography", "Corporate"],
    client: "Plancorp",
    description: "Photo gallery for Plancorp.",
    title: "Plancorp Photo Gallery",
    image_src: "/images/work-gallery-cover-images/photography/plancorp.png",
    featured: "featured-photography",
    slug: "plancorp-photo-gallery",
  },
  {
    category: ["Photography", "Education"],
    client: "Washington University",
    description: "Photo gallery for Washington University.",
    title: "Washington University Photo Gallery",
    image_src:
      "/images/work-gallery-cover-images/photography/washington-university.png",
    featured: "featured-photography",
    slug: "washington-university-photo-gallery",
  },
  {
    category: ["Photography", "Corporate"],
    client: "Rottler Pest Control",
    description: "Photo gallery for Rottler Pest Control.",
    title: "Rottler Pest Control Photo Gallery",
    image_src: "/images/work-gallery-cover-images/photography/rottler.png",
    featured: "",
    slug: "rottler-pest-control-photo-gallery",
  },
  {
    category: ["Photography", "Product Photography", "Medical", "Corporate"],
    client: "bioMérieux",
    description: "Photo gallery for bioMérieux medical devices.",
    title: "bioMérieux Photo Gallery",
    image_src: "/images/work-gallery-cover-images/photography/bmx.png",
    featured: "featured-product-photography",
    slug: "bioMerieux-photo-gallery",
  },
  {
    category: ["Photography", "Product Photography", "Corporate"],
    client: "CoreLink",
    description: "Photo gallery for CoreLink products.",
    title: "CoreLink Photo Gallery",
    image_src: "/images/work-gallery-cover-images/photography/core-link.png",
    featured: "featured-product-photography",
    slug: "corelink-photo-gallery",
  },
  {
    category: ["Photography", "Product Photography", "Corporate"],
    client: "Real American Muscle",
    description: "Photo gallery for Real American Muscle.",
    title: "Real American Muscle Photo Gallery",
    image_src:
      "/images/work-gallery-cover-images/photography/real-american-muscle.png",
    featured: "featured-product-photography",
    slug: "real-american-muscle-photo-gallery",
  },
  {
    category: ["Photography", "Corporate"],
    client: "IFF",
    description: "Photo gallery for IFF.",
    title: "IFF Photo Gallery",
    image_src: "/images/photographyWorkSamples/iff/01.webp",
    featured: "featured-photography",
    slug: "iff-photo-gallery",
  },
  {
    category: ["Corporate", "Video Editing", "Video Production"],
    client: "Tiller-Hewitt HealthCare Strategies",
    description:
      "A promotional video for Tiller-Hewitt HealthCare Strategies. Produced by Mike Martin Media.",
    title: "Tiller-Hewitt HealthCare Strategies",
    image_src:
      "https://image.mux.com/InuffvovdpvcE3hT6S017xFv3qUP8WZFjWKv01SCloUbc/thumbnail.webp?width=1920&height=1080&time=07",
    featured: "",
    slug: "tiller-hewitt-healthcare-strategies",
    playback_id: "InuffvovdpvcE3hT6S017xFv3qUP8WZFjWKv01SCloUbc",
  },
  {
    category: ["Medical", "Animation", "Video Editing"],
    client: "Harbinger Health",
    description:
      "An animated video for Harbinger Health. Produced by Mike Martin Media.",
    title: "Harbinger Health - Resolve",
    image_src:
      "https://image.mux.com/n00VeL9Uo8JMKaBD5WRacffCh7501R1cjrPMZngVPVIMA/thumbnail.webp?width=1920&height=1080&time=21.25",
    featured: "",
    slug: "harbinger-health",
    playback_id: "n00VeL9Uo8JMKaBD5WRacffCh7501R1cjrPMZngVPVIMA",
  },
  {
    category: ["Case Study", "Education", "Video Production"],
    client: "Washington University in St. Louis",
    description: "",
    mux_title: "washu-case-study-people-of-the-plan",
    title: "School of Continuing & Professional Studies",
    image_src:
      "https://image.mux.com/00sfSproISGGO00iyCl7p1pO1eScJ01vtUWPj55z004SP44/thumbnail.webp?width=1920&height=1080&time=12",
    featured: "",
    slug: "washu-case-study-people-of-the-plan",
    playback_id: "00sfSproISGGO00iyCl7p1pO1eScJ01vtUWPj55z004SP44",
    orientation: "horizontal",
  },
  {
    // id: "BeftU6Kems01qacztypoakEKPK5np3WwB5yR02EMk8qcA",
    category: ["Education", "Case Study", "Video Production"],
    client: "Washington University in St. Louis",
    description: "",
    mux_title: "washu-case-study-video-2",
    title: "Digital Intelligence & Innovation Accelerator",
    image_src:
      "https://image.mux.com/BeftU6Kems01qacztypoakEKPK5np3WwB5yR02EMk8qcA/thumbnail.webp?width=1920&height=1080&time=04",
    featured: "",
    slug: "washu-case-study-video-2",
    playback_id: "BeftU6Kems01qacztypoakEKPK5np3WwB5yR02EMk8qcA",
    orientation: "horizontal",
  },
  {
    category: ["Case Study", "Education", "Video Production"],
    client: "Washington University in St. Louis",
    description: "",
    mux_title: "washu-case-study-video-3",
    title: "Center for the Environment",
    image_src:
      "https://image.mux.com/JrTVAliKf01Ot7lWyjCW6vXyf8WLwYJyP15DSzSpWlz4/thumbnail.webp?width=1920&height=1080&time=04",
    featured: "",
    slug: "washu-case-study-video-3",
    playback_id: "JrTVAliKf01Ot7lWyjCW6vXyf8WLwYJyP15DSzSpWlz4",
    orientation: "horizontal",
  },
  {
    category: ["Case Study", "Nonprofit", "Video Production"],
    client: "Circus Harmony",
    description: "",
    mux_title: "circus-harmony-case-study-video",
    title: "Nathan",
    image_src:
      "https://image.mux.com/Tk6HdpoJ77V1JHESDJA21QVhq8WXJ4tKlhfPIvl5Hwc/thumbnail.webp?width=1920&height=1080&time=01",
    featured: "",
    slug: "circus-harmony-nathan",
    playback_id: "Tk6HdpoJ77V1JHESDJA21QVhq8WXJ4tKlhfPIvl5Hwc",
    orientation: "horizontal",
  },
  {
    category: ["Case Study", "Nonprofit", "Video Production"],
    client: "Circus Harmony",
    description: "",
    mux_title: "circus-harmony-case-study-video",
    title: "Nathan",
    image_src:
      "https://image.mux.com/Tk6HdpoJ77V1JHESDJA21QVhq8WXJ4tKlhfPIvl5Hwc/thumbnail.webp?width=1920&height=1080&time=010",
    featured: "",
    slug: "circus-harmony-nathan",
    playback_id: "Tk6HdpoJ77V1JHESDJA21QVhq8WXJ4tKlhfPIvl5Hwc",
    orientation: "horizontal",
  },
  {
    category: ["Case Study", "Nonprofit", "Video Production"],
    client: "Circus Harmony",
    description: "",
    mux_title: "circus-harmony-case-study-video",
    title: "Nathan",
    image_src:
      "https://image.mux.com/Tk6HdpoJ77V1JHESDJA21QVhq8WXJ4tKlhfPIvl5Hwc/thumbnail.webp?width=1920&height=1080&time=03",
    featured: "",
    slug: "circus-harmony-nathan",
    playback_id: "Tk6HdpoJ77V1JHESDJA21QVhq8WXJ4tKlhfPIvl5Hwc",
    orientation: "horizontal",
  },
  {
    category: [
      "Corporate",
      "Video Editing",
      "Video Production",
      "Case Study",
      // "Social Media",
    ],
    client: "Smith & Saint Talent Agency",
    description: "",
    mux_title: "smith-saint-panera",
    title: "Mix and Match with the Stars",
    image_src:
      "https://image.mux.com/NPVK80292isMIo2n5x02j00u3u00pprN3Azi5aaqxO5YWx00/thumbnail.webp?width=320&height=568&time=26",
    featured: "",
    slug: "smith-saint-panera",
    playback_id: "NPVK80292isMIo2n5x02j00u3u00pprN3Azi5aaqxO5YWx00",
    orientation: "vertical",
  },
  {
        category: [
          "Medical",
          "Video Editing",
          "Video Production",
          "Case Study",
        ],
        client: "Siteman Cancer Center",
        description:
          "The updated Mammography Van patient education video provides patients with a clear and welcoming overview of what to expect during their visit, while supporting Siteman's ongoing outreach and early detection efforts.",
        mux_title: "siteman-cancer-center",
        title: "Siteman Cancer Center - Mammography Van",
        image_src:
          "https://image.mux.com/Hwh01HHmGfBtLqlOwGyyVjS01yJtpFETmFMjtigAo3i38/thumbnail.webp?width=1920&height=1080&time=03",
        featured: "",
        slug: "siteman-cancer-center",
        playback_id: "Hwh01HHmGfBtLqlOwGyyVjS01yJtpFETmFMjtigAo3i38",
        orientation: "horizontal",
      },
  // {
  //   category: [],
  //   client: "",
  //   description: "",
  //   title: "",
  //   image_src: "",
  //
  //   featured: "",
  //   slug: "",
  //   playback_id: "",
  // },
  // {
  //   category: ["Photography", ""],
  //   client: "",
  //   description: "Photo gallery for ",
  //   title: "Photo Gallery",
  //   image_src:
  //     "/images/work-gallery-cover-images/photography/.png",
  //
  //   featured: "featured-photography",
  //   slug: "",
  // },
  //   {
  //     category: ["Video Editing", "Video Production"],
  //     client: "",
  //     title: "",
  //     image_src: "/images/work-gallery-cover-images/",
  //     src: "https://player.vimeo.com/video/&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  //   },
];
