export const workSampleData = [
  {
    category: ["Corporate", "Video Editing", "Video Production", "Drone"],
    client: "Synergy Living",
    title: "Synergy Living Kirkwood Development",
    image_src: "/images/work-gallery-cover-images/synergy-living-cover.jpg",
    src: "https://player.vimeo.com/video/1024802262?h=7af899a007&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    featured: "featured-drone",
  },
  {
    category: ["Corporate", "Video Editing", "Video Production", "Animation"],
    client: "FSI",
    title: "FSI Facilities",
    image_src: "/images/work-gallery-cover-images/fsi-cover.jpg",
    src: "https://player.vimeo.com/video/1035739098?h=7af899a007&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Nonprofit", "Video Editing", "Video Production"],
    client: "Joshua Chamberlain Society",
    title: "Gala Fund-A-Need",
    image_src: "/images/work-gallery-cover-images/jcs-cover.jpg",
    src: "https://player.vimeo.com/video/838407827?h=3668c77c36&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    featured: "featured-video-production",
  },
  {
    category: ["Nonprofit", "Video Editing", "Video Production"],
    client: "USO of Missouri",
    title: "Holiday Block Leave",
    image_src: "/images/work-gallery-cover-images/uso-of-mo-cover.jpg",
    src: "https://player.vimeo.com/video/792679501?h=8a339c0ff3&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    featured: "featured-video-editing",
  },
  {
    category: ["Corporate", "Drone", "Video Editing", "Video Production"],
    client: "ARTCO",
    title: "Recruitment",
    image_src: "/images/work-gallery-cover-images/artco-cover.jpg",
    src: "https://player.vimeo.com/video/901619462?h=4ab57402b0&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    featured: "featured-drone",
  },
  {
    category: ["Corporate", "Drone", "Video Editing", "Video Production"],
    client: "MMM",
    title: "In Grand Center",
    image_src: "/images/work-gallery-cover-images/mmm-cover.jpg",
    src: "https://player.vimeo.com/video/799944146?h=7ce1e106da&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    featured: "featured-video-editing",
  },
  {
    category: ["Corporate", "Drone", "Video Editing", "Video Production"],
    client: "Girl Scouts of Eastern Missouri",
    title: "Padde Raise",
    image_src: "/images/work-gallery-cover-images/gsem-cover.jpg",
    src: "https://player.vimeo.com/video/796701498?h=2711ae04fb&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    featured: "featured-drone",
  },
  // {
  //   category: ["Corporate", "Video Editing", "Video Production"],
  //   client: "MiTek",
  //   title: "Houston Groundbreaking",
  //   image_src: "/images/work-gallery-cover-images/mitek-cover.jpg",
  //   src: "https://player.vimeo.com/video/779302587?h=59cf20066f&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  //   featured: "featured-video-editing",
  // },
  {
    category: ["Corporate", "Video Editing", "Video Production"],
    client: "Club Fitness",
    title: "Share to Inspire",
    image_src: "/images/work-gallery-cover-images/club-fitness-share-cover.jpg",
    src: "https://player.vimeo.com/video/1050824685?h=0a70bae50f&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    featured: "featured-video-production",
  },
  {
    category: ["Corporate", "Video Editing", "Video Production", "Drone"],
    client: "Music at the Intersection",
    title: "Highlight",
    image_src: "/images/work-gallery-cover-images/mati-cover.jpg",
    src: "https://player.vimeo.com/video/862940886?h=48731807d6&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    featured: "featured-drone",
  },
  {
    category: ["Corporate", "Video Editing", "Video Production", "Drone"],
    client: "Five Star Auto Body",
    title: "Recruitment",
    image_src: "/images/work-gallery-cover-images/five-star-auto-cover.jpg",
    src: "https://player.vimeo.com/video/755292157?h=e641dc365b&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    featured: "featured-video-production",
  },
  {
    category: ["Education", "Drone", "Video Editing", "Video Production"],
    client: "Eden Theological Seminary",
    title: "Recruitment",
    image_src: "/images/work-gallery-cover-images/eden-theological-cover.jpg",
    src: "https://player.vimeo.com/video/829943828?h=c4be815d3e&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Education", "Video Editing", "Video Production"],
    client: "Murphy Company",
    title: "Training Demo",
    image_src: "/images/work-gallery-cover-images/murphy-company-cover.jpg",
    src: "https://player.vimeo.com/video/823476966?h=4efdfbf093&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Education", "Video Editing", "Video Production"],
    client: "Washington University",
    title: "Founders Day",
    image_src: "/images/work-gallery-cover-images/wash-u-cover.jpg",
    src: "https://player.vimeo.com/video/880289545?h=3226a6bf33&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    featured: "featured-video-production",
  },
  {
    category: ["Education", "Video Editing", "Video Production"],
    client: "Johnstone Sales",
    title: "Demo",
    image_src: "/images/work-gallery-cover-images/johnston-sales-cover.jpg",
    src: "https://player.vimeo.com/video/802838459?h=8ee67196b0&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Education", "Video Editing", "Video Production"],
    client: "Washington University Olin Business School",
    title: "Big Idea Bounce Contest",
    image_src: "/images/work-gallery-cover-images/wash-u-olin-cover.jpg",
    src: "https://player.vimeo.com/video/820666152?h=e4f8f6c5f6&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Education", "Video Editing", "Video Production"],
    client: "BioSTL",
    title: "Internships",
    image_src: "/images/work-gallery-cover-images/bio-stl-cover.jpg",
    src: "https://player.vimeo.com/video/849274086?h=843ea55285&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    featured: "featured-video-production",
  },
  {
    category: ["Medical", "Video Editing", "Video Production"],
    client: "SSM Cardinal Glennon",
    title: "Residency Recruitment",
    image_src: "/images/work-gallery-cover-images/ssm-cardinal-glennon-cover.jpg",
    src: "https://player.vimeo.com/video/872654095?h=2fbe224539&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    featured: "featured-video-editing",
  },
  {
    category: ["Medical", "Video Editing", "Video Production", "Drone"],
    client: "Washington University Emergency Medicine",
    title: "Residency Recruitment",
    image_src:
      "/images/work-gallery-cover-images/wash-u-emergency-med-cover.jpg",
    src: "https://player.vimeo.com/video/866533299?h=90843c1f39&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Medical", "Video Editing", "Video Production", "Drone"],
    client: "Washington University Neuromuscular Medicine",
    title: "Fellowship Recruitment",
    src: "https://player.vimeo.com/video/900179612?h=690b0e7751&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    image_src: "/images/work-gallery-cover-images/wash-u-nm-med-cover.jpg",
    featured: "featured-video-editing",
  },
  {
    category: ["Medical", "Video Editing", "Video Production", "Drone"],
    client: "Siteman Cancer Center",
    title: "Brain Tumor Center",
    image_src: "/images/work-gallery-cover-images/siteman-cover.jpg",
    src: "https://player.vimeo.com/video/842642479?h=a33d343fee&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Medical", "Video Editing", "Video Production"],
    client: "Alton Memorial Hospital Foundation",
    title: "Duck Pluckers Ball",
    image_src: "/images/work-gallery-cover-images/alton-memorial-cover.png",
    src: "https://player.vimeo.com/video/905668122?h=44f7031f29&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Medical", "Video Editing", "Video Production", "Drone"],
    client: "St Louis Children's Hospital",
    title: "Employee Giving",
    image_src: "/images/work-gallery-cover-images/childrens-hospital-cover.jpg",
    src: "https://player.vimeo.com/video/790947100?h=a476fa3e19&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Medical", "Video Editing", "Video Production", "Drone"],
    client: "Ascension Healthcare",
    title: "St. Vincent",
    image_src: "/images/work-gallery-cover-images/ascension-cover.jpg",
    src: "https://player.vimeo.com/video/942507749?h=5211a400f9&&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    featured: "featured-drone",
  },
  {
    category: ["Medical", "Video Editing", "Video Production"],
    client: "SSM Health",
    title: "Industrial Rehabilitaion Center",
    image_src: "/images/work-gallery-cover-images/ssm-health-cover.jpg",
    src: "https://player.vimeo.com/video/943675631?h=5cd1437083&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Nonprofit", "Video Editing", "Video Production"],
    client: "Barnes-Jewish Hospital Foundation",
    title: "Illumination Gala",
    image_src: "/images/work-gallery-cover-images/bjaf-gala-cover.jpg",
    src: "https://player.vimeo.com/video/840455005?h=8cf0180342&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Nonprofit", "Video Editing", "Video Production"],
    client: " Ollie Hinkle Heart Foundation",
    title: "Gala Fund-A-Need",
    image_src: "/images/work-gallery-cover-images/ollie-hinkle-cover.jpg",
    src: "https://player.vimeo.com/video/812985606?h=a0fe83b76b&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    featured: "featured-video-production",
  },
  {
    category: ["Nonprofit", "Video Editing", "Video Production"],
    client: "Central Institute for the Deaf",
    title: "Out Loud",
    image_src: "/images/work-gallery-cover-images/cid-cover.jpg",
    src: "https://player.vimeo.com/video/825959288?h=46ba69e53b&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  // {
  //   category: ["Nonprofit", "Video Editing", "Video Production"],
  //   client: "Cardinal Ritter Senior Services",
  //   title: "Gala Fund-A-Need",
  //   image_src: "/images/work-gallery-cover-images/cardinal-ritter-cover.jpg",
  //   src: "https://player.vimeo.com/video/700538510?h=350078ccdd&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  // },
  {
    category: ["Nonprofit", "Video Editing", "Video Production"],
    client: "Cystic Fibrosis Foundation",
    title: "Gala Fund-A-Need",
    image_src: "/images/work-gallery-cover-images/cystic-fibrosis-cover.jpg",
    src: "https://player.vimeo.com/video/884469475?h=38bff527f4&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Nonprofit", "Video Editing", "Video Production"],
    client: "Kids in the Middle",
    title: "Mission Promo",
    image_src: "/images/work-gallery-cover-images/kitm-cover.jpg",
    src: "https://player.vimeo.com/video/862525134?h=722087be67&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  // {
  //   category: ["Nonprofit", "Livestream", "Video Editing", "Video Production"],
  //   client: "Spirit of Provident",
  //   title: "Gala Livestream",
  //   image_src:
  //     "/images/work-gallery-cover-images/provident-livestream-cover.jpg",
  //   src: "https://player.vimeo.com/video/676469724?h=86dadc6885&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  // },
  {
    category: ["Animation", "Medical", "Video Editing", "Video Production"],
    client: "St. Louis Children's Hospital",
    title: "What to Expect - Colonoscopy",
    image_src:
      "/images/work-gallery-cover-images/childrens-hospital-animation-cover.jpg",
    src: "https://player.vimeo.com/video/823498854?h=49fb6c4ebf&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Animation", "Education", "Video Editing", "Video Production"],
    client: "Washington University",
    title: "Always Olin",
    image_src: "/images/work-gallery-cover-images/wash-u-animation-cover.jpg",
    src: "https://player.vimeo.com/video/944136129?h=701f2488bb&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Animation", "Education", "Video Editing", "Video Production"],
    client: "Washington University",
    title: "Olin MBA",
    image_src:
      "/images/work-gallery-cover-images/wash-u-olin-business-animation-cover.jpg",
    src: "https://player.vimeo.com/video/823498955?h=815218068d&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Corporate", "Video Editing", "Video Production"],
    client: "Club Fitness",
    title: "15 Second Promo",
    image_src: "/images/work-gallery-cover-images/club-fitness-promo-cover.jpg",
    src: "https://player.vimeo.com/video/1042932679?h=8032012bdc&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Corporate", "Video Editing", "Video Production", "Drone"],
    client: "McCarthy Building Companies",
    title: "Project Spotlight",
    image_src: "/images/work-gallery-cover-images/mccarthy-cover.jpg",
    src: "https://player.vimeo.com/video/1004659940?h=83dc5242f5&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    featured: "featured-drone",
  },
  {
    category: ["Medical", "Video Editing", "Video Production"],
    client: "St. Louis Children's Hospital Foundation",
    title: "CMN Patient Ambassadors",
    image_src: "/images/work-gallery-cover-images/stlouis-childrens-hospital-foundation-cover.jpg",
    src: "https://player.vimeo.com/video/930793149?h=2a6f6a2764&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
    featured: "featured-video-editing",
  },
  {
    category: ["Education", "Video Editing", "Video Production"],
    client: "The Marianists",
    title: "Marianist DIL",
    image_src: "/images/work-gallery-cover-images/marianists-cover.jpg",
    src: "https://player.vimeo.com/video/942118194?h=c9ee03bedc&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Education", "Livestream", "Video Editing", "Video Production"],
    client: "Sam Fox School",
    title: "Sam Fox School Awards of Distinction 2023",
    image_src: "/images/work-gallery-cover-images/sam-fox-school-cover.jpg",
    src: "https://player.vimeo.com/video/815736728?badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Photography", "Nonprofit"],
    client: "Catholic Charities of St. Louis",
    title: "Catholic Charities of St. Louis Photo Gallery",
    image_src:
      "/images/work-gallery-cover-images/photography/catholic-charities-gallery-cover.png",
    src: "",
  },
  {
    category: ["Photography"],
    client: "Prasino",
    title: "Prasino Photo Gallery",
    image_src:
      "/images/work-gallery-cover-images/photography/prasino-gallery-cover.png",
    src: "",
  },
  {
    category: ["Photography"],
    client: "Club Fitness",
    title: "Club Fitness Photo Gallery",
    image_src:
      "/images/work-gallery-cover-images/photography/club-fitness-gallery-cover.png",
    src: "",
  },
  {
    category: ["Video Editing", "Video Production"],
    client: "CID",
    title: "CID Out Loud",
    image_src: "/images/work-gallery-cover-images/cid-outloud-cover.jpg",
    src: "https://player.vimeo.com/video/1049078237?h=6f4c1feb6f&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
  {
    category: ["Video Editing", "Video Production"],
    client: "Evertrue",
    title: "ET IL Social Opportunities",
    image_src: "/images/work-gallery-cover-images/evertrue-cover.jpg",
    src: "https://player.vimeo.com/video/1033942065?h=07edd2100d&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
  },
//   {
//     category: ["Video Editing", "Video Production"],
//     client: "",
//     title: "",
//     image_src: "/images/work-gallery-cover-images/",
//     src: "https://player.vimeo.com/video/&badge=0&autopause=0&player_id=0&app_id=58479&controls=1&loop=1&muted=0&byline=0&portrait=0",
//   },
];
