 export const caseStudiesPageBannerText = {
  title: "Case Studies",
  heading: "What Collaboration Looks Like in Practice",
  text: "If you are considering a video partner, you want more than a highlight reel — you want proof. Our case studies take a closer look at the projects we've created, the challenges our clients faced, and how video helped them communicate more clearly and effectively.",
  text2:
    "These stories highlight how thoughtful video production can build trust, drive engagement, and support real business and mission-driven goals.",
};

export const howWeSupportOurClients = {
  heading: "How We Support Our Clients",
  sub_heading:
    "Our approach: listen first, plan carefully, and deliver work that serves a purpose.",
  list_items: [
    {
      label: "Strategic Planning & Creative Direction ",
      description:
        "We help define messaging, audience, and objectives before production begins",
      image: "/images/case-studies/support-images/greeting.webp",
    },
    {
      label: "Production & Field Crews",
      description:
        "Professional, efficient and flexible crews that keep shoots running smoothly and on schedule.",
      image: "/images/case-studies/support-images/prompter.webp",
    },
    {
      label: "Interviews & Messaging Support",
      description:
        "Guiding executives, staff, and clients to feel comfortable and authentic on camera.",
      image: "/images/case-studies/support-images/interview.webp",
    },
    {
      label: "Post-Production & Editing",
      description:
        "Clear storytelling, clean pacing, and polished multi-format delivery",
      image: "/images/case-studies/support-images/edit.webp",
    },
    {
      label: "Motion Graphics & Visual Enhancements ",
      description:
        "Purposeful graphics that clarify information and support the story.",
      image: "/images/case-studies/support-images/motion-graphics.webp",
    },
  ],
};

export const caseStudies = [
  {
    slug: "washu-advancing-our-mission",
    client: "Washington University in St. Louis",
    title: "WashU: Advancing Our Mission",
    short_title: "Advancing Our Mission",
    campaign: "Advancing Our Mission: Strategic Plan 2019-25",
    short_campaign: "Strategic Plan 2019-2025",
    format: "Video Vignette Series (5 videos)",
    short_format: "Video Vignette Series",
    challenge: [
      "As Washington University concluded its Strategic Plan for 2019 to 2025, leadership wanted to recognize the people behind the work — elevating early contributors, capturing their personal investment, and sharing authentic stories that could inspire the broader WashU community through ongoing campaign communications.",
      "This project focused on real pride, collaboration, and the earned feeling of “we actually did this.”",
    ],
    approach: [
      "Mike Martin Media partnered with WashU to produce a five-part video vignette series featuring on-camera conversations with key leaders and contributors across initiatives.",
      "Filmed on campus, each interview was guided by a producer to feel natural and unscripted. A multi-camera setup provided visual variety while maintaining an intimate, conversational tone. Curated campus locations served as intentional backdrops, grounding each story in WashU's environment and mission.",
      "Subtle graphics, music, and intro/outro elements created cohesion across the series and connected each vignette back to the larger campaign and hero video. Campus and subject b-roll was integrated throughout to add visual depth and context.",
    ],
    result: [
      "Here is an example from the series that showcases the collaboration, ownership, and impact behind WashU's Strategic Plan.",
      "These videos now serve as core storytelling assets within WashU's monthly communications, supporting the Advancing Our Mission campaign while honoring the people who helped bring it to life.",
    ],
    partnership: {
      type: "long-term",
      text: [
        "Mike Martin Media has partnered with Washington University in St. Louis for more than 17 years, collaborating across a wide range of initiatives and campaigns.",
        "We're grateful for the continued trust WashU places in our team and for the opportunity to help tell stories that matter — especially those centered on people, purpose, and lasting impact.",
      ],
    },
    preview_image: {
      alt: "The campus of Washington University in St. Louis photographed from a drone",
      url: "https://image.mux.com/00sfSproISGGO00iyCl7p1pO1eScJ01vtUWPj55z004SP44/thumbnail.webp?width=576&height=324&time=04",
      width: 576,
      height: 324,
    },
    banner_images: [
      {
        url: "/images/case-studies/wash-u/banner-images/0.png",
        alt: "The campus of Washington University in St. Louis photographed from a drone",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/banner-images/1.png",
        alt: "The MMM team setting up for a photo shoot on the campus of Washington University in St. Louis",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/banner-images/2.png",
        alt: "A sign on the campus of Washington University in St. Louis that reads 'Washington University in St. Louis, Danforth Campus'",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/banner-images/3.png",
        alt: "The MMM team setting up for a photo shoot on the campus of Washington University in St. Louis",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/banner-images/4.png",
        alt: "A Washington University medical team reviews x-rays with a patient in a hospital",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/banner-images/5.png",
        alt: "The MMM team setting up for a photo shoot on the campus of Washington University in St. Louis",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/banner-images/6.png",
        alt: "The campus of Washington University in St. Louis photographed from a drone",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/banner-images/7.png",
        alt: "A team of Washington University researchers on a reiverbank with a drone",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/banner-images/8.png",
        alt: "Students on the campus of Washington University in St. Louis",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/banner-images/9.png",
        alt: "A graduate of Washington University in a cap and gown shows off an award",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/banner-images/10.png",
        alt: "Staff and faculty of Washington University in a group discussion on the campus",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/banner-images/11.png",
        alt: "An instructor at Washington Univeristy gives a lecture in front of a projection screen and a chalkboard in a classroom",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/banner-images/12.png",
        alt: "Participants in a panel discussion seated in chairs in front of an audience on the campus of Washington University in St. Louis",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
    ],
    landscape_images: [
      {
        url: "/images/case-studies/wash-u/landscape/0.webp",
        alt: "A sign on the campus of Washington University in St. Louis that reads 'Washington University in St. Louis, Danforth Campus'",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/landscape/1.webp",
        alt: "The MMM team setting up for a photo shoot on the campus of Washington University in St. Louis",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/landscape/2.webp",
        alt: "A graduate of Washington University in a cap and gown shows off an award",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/landscape/3.webp",
        alt: "The MMM team setting up for a photo shoot on the campus of Washington University in St. Louis",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/landscape/4.webp",
        alt: "Washington University reasearchers in a laboratory setting",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/landscape/5.webp",
        alt: "The MMM team setting up for a photo shoot on the campus of Washington University in St. Louis",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/landscape/6.webp",
        alt: "A group of Washington University instructors seated around a table, with one person standing and writing on a white board.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/landscape/7.webp",
        alt: "A drone photograph of the Washington University Medical Campus in St. Louis",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/landscape/8.webp",
        alt: "Staff and faculty of Washington University in a group discussion on the campus",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/landscape/9.webp",
        alt: "Washington University reasearchers in a laboratory setting",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/landscape/10.webp",
        alt: "An instructor at Washington Univeristy gives a lecture in front of a projection screen and a chalkboard in a classroom",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/wash-u/landscape/11.webp",
        alt: "Participants in a panel discussion seated in chairs in front of an audience on the campus of Washington University in St. Louis",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
    ],
    portrait_images: [
      {
        url: "/images/case-studies/wash-u/portrait/0.webp",
        alt: "The MMM team onsite for a photo shoot on the campus of Washington University in St. Louis",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/wash-u/portrait/1.webp",
        alt: "The MMM team onsite for a photo shoot on the campus of Washington University in St. Louis",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/wash-u/portrait/2.webp",
        alt: "The MMM team onsite for a photo shoot on the campus of Washington University in St. Louis",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/wash-u/portrait/3.webp",
        alt: "The MMM team onsite for a photo shoot on the campus of Washington University in St. Louis",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/wash-u/portrait/4.webp",
        alt: "The MMM team onsite for a photo shoot on the campus of Washington University in St. Louis",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/wash-u/portrait/5.webp",
        alt: "The MMM team onsite for a photo shoot on the campus of Washington University in St. Louis",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/wash-u/portrait/6.webp",
        alt: "The MMM team onsite for a photo shoot on the campus of Washington University in St. Louis",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/wash-u/portrait/7.webp",
        alt: "The MMM team onsite for a photo shoot on the campus of Washington University in St. Louis",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/wash-u/portrait/8.webp",
        alt: "The MMM team onsite for a photo shoot on the campus of Washington University in St. Louis",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/wash-u/portrait/9.webp",
        alt: "The MMM team onsite for a photo shoot on the campus of Washington University in St. Louis",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/wash-u/portrait/10.webp",
        alt: "The MMM team onsite for a photo shoot on the campus of Washington University in St. Louis",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/wash-u/portrait/11.webp",
        alt: "The MMM team onsite for a photo shoot on the campus of Washington University in St. Louis",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/wash-u/portrait/12.webp",
        alt: "The MMM team onsite for a photo shoot on the campus of Washington University in St. Louis",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/wash-u/portrait/13.webp",
        alt: "The MMM team onsite for a photo shoot on the campus of Washington University in St. Louis",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/wash-u/portrait/14.webp",
        alt: "The MMM team onsite for a photo shoot on the campus of Washington University in St. Louis",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/wash-u/portrait/15.webp",
        alt: "The MMM team onsite for a photo shoot on the campus of Washington University in St. Louis",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
    ],
    videos: [
      {
        category: ["Case Study", "Education", "Video Production"],
        client: "Washington University in St. Louis",
        description: "",
        mux_title: "washu-case-study-video-3",
        title: "Washington University - Center for the Environment",
        image_src:
          "https://image.mux.com/JrTVAliKf01Ot7lWyjCW6vXyf8WLwYJyP15DSzSpWlz4/thumbnail.webp?width=1920&height=1080&time=04",
        featured: "",
        slug: "washu-case-study-video-3",
        playback_id: "JrTVAliKf01Ot7lWyjCW6vXyf8WLwYJyP15DSzSpWlz4",
        orientation: "horizontal",
      },
    ],
  },
  {
    slug: "circus-harmony",
    client: "Circus Harmony",
    title: "Circus Harmony: 25 Years of Impact",
    short_title: "25 Years of Impact",
    short_campaign: "25th Anniversary Celebration",
    campaign: "25th Anniversary Celebration",
    format: "Video Vignette Series (25 videos)",
    short_format: "Video Vignette Series",
    challenge: [
      "As Circus Harmony approached its 25th anniversary as a nonprofit organization, the team wanted to celebrate the milestone by capturing the voices of alumni whose lives were shaped by the program. The goal was to produce a collection of authentic alumni stories that could be shared across social media, the organization's website, and anniversary campaign communications, while also contributing to a longer-form celebration video.",
      "Beyond documenting the past, the project aimed to highlight the lasting impact of Circus Harmony's mission — demonstrating how the acrobatic arts can build confidence, community, and life-changing opportunities for young people.",
    ],
    approach: [
      "For the 25-part video vignette series, interviews were recorded at the Mike Martin Media production studio in St. Louis and remotely with alumni located across the United States and internationally, including participants in Israel. To deepen the narrative, the production team incorporated more than a decade of archival footage from Circus Harmony performances and programs previously captured by MMM. ",
    ],
    result: [
      "The 25 Years of Circus Harmony video series celebrates the organization's legacy through the voices of its alumni. Here is a taste of the short-form videos that were released throughout the year on social media, helping build awareness and excitement leading up to Circus Harmony's annual Soirée fundraising event.",
      "Together, the vignettes showcase the impact of Circus Harmony's programs while reinforcing the organization's mission — demonstrating how nonprofit storytelling through video can inspire audiences, strengthen community connections, and support fundraising efforts.",
    ],
    partnership: {
      type: "long-term",
      text: [
        "Circus Harmony was one of the earliest clients of Mike Martin Media, and our team has had the privilege of capturing their annual performances and programs for many years. It's an honor to help celebrate their 25th anniversary and to continue partnering with an organization dedicated to changing lives through the circus arts.",
      ],
    },
    preview_image: {
      alt: "The Circus Harmony 25th Anniversary logo, which features a red banner that says '25th Anniversary' and silhouettes of circus performers on and around the banner",
      url: "https://image.mux.com/Tk6HdpoJ77V1JHESDJA21QVhq8WXJ4tKlhfPIvl5Hwc/thumbnail.webp?width=576&height=324&time=22",
      width: 576,
      height: 324,
    },
    banner_images: [
      {
        url: "/images/case-studies/circus-harmony/banner-images/0.webp",
        alt: "A Circus Harmony aerial performer suspended from a rope high above the ground while performing in front of an audience",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/circus-harmony/banner-images/1.webp",
        alt: "The MMM team shooting an interview video with someone from Circus Harmony",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/circus-harmony/banner-images/2.webp",
        alt: "A Circus Harmony performer dancing with chairs and hoops in front of an audience",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/circus-harmony/banner-images/3.webp",
        alt: "The MMM team shooting an interview video with someone from Circus Harmony",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/circus-harmony/banner-images/4.webp",
        alt: "A Circus Harmony performer doing a handstand while a group of performers kneel around them in a circle in front of an audience",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/circus-harmony/banner-images/5.webp",
        alt: "The MMM team shooting an interview video with someone from Circus Harmony",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
    ],
    landscape_images: [
      {
        url: "/images/case-studies/circus-harmony/landscape/0.webp",
        alt: "A Circus Harmony aerial performer suspended from a rope high above the ground while performing in front of an audience",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/circus-harmony/landscape/1.webp",
        alt: "The MMM team shooting an interview video with someone from Circus Harmony",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/circus-harmony/landscape/2.webp",
        alt: "A Circus Harmony performer doing a handstand while a group of performers kneel around them in a circle in front of an audience",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/circus-harmony/landscape/3.webp",
        alt: "The MMM team shooting an interview video with someone from Circus Harmony",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/circus-harmony/landscape/4.webp",
        alt: "A group of Circus Harmony performers form a human pyramid in front of an audience",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/circus-harmony/landscape/5.webp",
        alt: "The MMM team shooting an interview video with someone from Circus Harmony",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/circus-harmony/landscape/6.webp",
        alt: "A Circus Harmony performer dancing with chairs and hoops in front of an audience",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
    ],
    portrait_images: [
      {
        url: "/images/case-studies/circus-harmony/portrait/0.webp",
        alt: "The MMM team shooting an interview video with someone from Circus Harmony",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/circus-harmony/portrait/1.webp",
        alt: "The MMM team shooting an interview video with someone from Circus Harmony",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
    ],
    videos: [
      {
        category: ["Case Study", "Nonprofit", "Video Production"],
        client: "Circus Harmony",
        description:
          "Circus Harmony Coach Laura shares her experience with the organization.",
        mux_title: "circus-harmony-case-study-video",
        title: "Circus Harmony Coach - Laura Lippert",
        image_src:
          "https://image.mux.com/P4ckNQA46Uy2zx6XbJi3hC4pz9gLN1GCL010172zqeATQ/thumbnail.webp?width=1920&height=1080&time=02",
        featured: "",
        slug: "circus-harmony-laura",
        playback_id: "P4ckNQA46Uy2zx6XbJi3hC4pz9gLN1GCL010172zqeATQ",
        orientation: "horizontal",
      },
    ],
  },
  {
    slug: "smith-saint-talent-agency",
    client: "Smith & Saint Talent Agency",
    brand_partner: "Panera Bread",
    title: "Smith & Saint Talent Agency: Panera Social Campaign",
    short_title: "Panera Social Campaign",
    campaign: "Mix & Match with the Stars",
    short_campaign: "Mix & Match with the Stars",
    format: "Commercial social media video",
    short_format: "Commercial Social Media Video",
    challenge: [
      "When Smith & Saint Talent Agency secured a brand partnership between Panera for their clients, dancers on the Dancing With the Stars tour, they needed a production partner who could move quickly. The team reached out to Mike Martin Media on a Wednesday afternoon with a request to film a branded social media commercial by Friday.",
      "With a tight timeline and talent schedules to coordinate, the goal was to produce a polished 60-second social media video promoting Panera's Mix & Match menu while capturing the personality and energy of the dancers featured in the campaign.",
    ],
    approach: [
      "The concept featured the dancers visiting Panera for lunch, highlighting their new Mix & Match menu through a playful interaction that builds to the familiar rhythm cue “five, six, seven, ate,” after a quick dance sequence.",
      "Our team captured the commercial on location using an efficient production setup designed to move quickly while maintaining the quality expected from a professional commercial video production team.",
    ],
    result: [
      "The final 60-second branded social media video combined Panera's product messaging with the high-energy style of the Dancing With the Stars performers.",
      "Delivered on an accelerated timeline, the video supported the brand partnership campaign while providing engaging content optimized for social media platforms.",
    ],
    partnership: {
      type: "new",
      text: [
        "This project began with a simple online search and a quick introduction, but it quickly turned into a great collaboration and our first project with Smith & Saint Talent Agency.",
        "Despite the short turnaround, the production ran smoothly from pre-production through delivery — a reminder that with the right team in place, even a fast-moving concept can quickly become polished commercial and social media content.",
        "We appreciated the opportunity to help bring their Panera Bread brand partnership campaign to life and hope to work together again in the future.",
      ],
    },
    preview_image: {
      alt: "The Panera Bread logo superimposed over a blurred out image of the Dancing With the Stars performers featured in the Mix & Match campaign seated at a table in a Panera restaurant",
      url: "/images/case-studies/preview-images/panera-preview-img.webp",
      width: 576,
      height: 324,
    },
    banner_images: [
      {
        url: "/images/case-studies/smith-saint/banner-images/1.png",
        alt: "Dancers from the Dancing With the Stars tour walking towards a Panera restaurant while a MMM photographer takes pictures of them.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/2.png",
        alt: "Dancers from the Dancing With the Stars tour walking through the door of a Panera restaurant while a MMM photographer takes pictures of them from the outside of the building.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/3.png",
        alt: "Dancers from the Dancing With the Stars tour walking through the door of a Panera restaurant while a MMM photographer takes pictures of them from the inside of the building.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/4.png",
        alt: "Dancers from the Dancing With the Stars tour reviewing the Panera menu at the counter while the MMM crew captures the moment.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/5.png",
        alt: "Dancers from the Dancing With the Stars tour reviewing the menu at the counter while the MMM crew captures the moment.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/6.png",
        alt: "Dancers from the Dancing With the Stars tour reviewing the menu at the counter while the MMM crew captures the moment.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/7.png",
        alt: "Dancers from the Dancing With the Stars tour placing their order at the counter while the MMM crew captures the moment.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/8.png",
        alt: "Dancers from the Dancing With the Stars tour dancing in front of the counter after placing their order.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/9.png",
        alt: "Dancers from the Dancing With the Stars tour dancing in front of the counter after placing their order.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/10.png",
        alt: "Dancers from the Dancing With the Stars tour dancing in front of the counter after placing their order while the MMM crew captures the moment.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/11.png",
        alt: "Dancers from the Dancing With the Stars tour dancing in front of the counter after placing their order while the MMM crew captures the moment.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/12.png",
        alt: "Dancers from the Dancing With the Stars tour dancing in front of the counter after placing their order while the MMM crew captures the moment.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/13.png",
        alt: "Dancers from the Dancing With the Stars tour dancing in front of the counter after placing their order while the MMM crew captures the moment.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/14.png",
        alt: "Dancers from the Dancing With the Stars tour seated around a table in a Panera restaurant talking with some fans while the MMM crew captures the moment.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/15.png",
        alt: "Dancers from the Dancing With the Stars tour seated around a table in a Panera restaurant the MMM crew captures the moment.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/16.png",
        alt: "Dancers from the Dancing With the Stars tour seated around a table in a Panera restaurant the MMM crew captures the moment.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/17.png",
        alt: "The MMM team photographers one of the dancers seated at a booth enjoying his lunch at a Panera restaurant.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/banner-images/18.png",
        alt: "A member of the MMM team holds a boom microphone over a group of dancers from the Dancing With the Stars tour seated in a booth at a Panera restaurant while they enjoy their meal.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
    ],
    portrait_images: [
      {
        url: "/images/case-studies/smith-saint/portrait/1.webp",
        alt: "Mikey from the MMM team shoots video of the dancers talking to each other in the parking lot before they enter the Panera restaurant.",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/smith-saint/portrait/2.webp",
        alt: "Mikey from the MMM team shoots video of the dancers from outside of the building as they enter the Panera restaurant.",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/smith-saint/portrait/3.webp",
        alt: "Mikey from the MMM team shoots video of the dancers from inside the Panera restaurant as they enter the building.",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/smith-saint/portrait/4.webp",
        alt: "Mikey from the MMM team shoots video of the dancers as they walk towards the counter to place their order.",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
      {
        url: "/images/case-studies/smith-saint/portrait/5.webp",
        alt: "The dancers from the Dancing With the Stars tour order their food at the counter while the MMM team captures the moment.",
        width: 1280,
        height: 1920,
        orientation: "portrait",
      },
    ],
    landscape_images: [
      {
        url: "/images/case-studies/smith-saint/landscape/0.webp",
        alt: "Dancers from the Dancing With the Stars tour walking towards a Panera restaurant while a MMM photographer takes pictures of them.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/landscape/1.webp",
        alt: "Dancers from the Dancing With the Stars tour walking through the door of a Panera restaurant while a MMM photographer takes pictures of them from the outside of the building.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/landscape/2.webp",
        alt: "Dancers from the Dancing With the Stars tour walking through the door of a Panera restaurant while a MMM photographer takes pictures of them from the inside of the building.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/landscape/3.webp",
        alt: "Dancers from the Dancing With the Stars tour reviewing the Panera menu at the counter while the MMM crew captures the moment.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/landscape/4.webp",
        alt: "Dancers from the Dancing With the Stars tour reviewing the Panera menu at the counter.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },

      {
        url: "/images/case-studies/smith-saint/landscape/5.webp",
        alt: "Dancers from the Dancing With the Stars tour dancing in front of the counter after placing their order.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/landscape/6.webp",
        alt: "Dancers from the Dancing With the Stars tour dancing in front of the counter after placing their order.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/landscape/7.webp",
        alt: "Dancers from the Dancing With the Stars tour dancing in front of the counter after placing their order while the MMM crew captures the moment.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },

      {
        url: "/images/case-studies/smith-saint/landscape/8.webp",
        alt: "Dancers from the Dancing With the Stars tour dancing in front of the counter after placing their order while the MMM crew captures the moment.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/landscape/9.webp",
        alt: "Dancers from the Dancing With the Stars tour dancing in front of the counter after placing their order while the MMM crew captures the moment.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },

      {
        url: "/images/case-studies/smith-saint/landscape/10.webp",
        alt: "Dancers from the Dancing With the Stars tour seated around a table in a Panera restaurant the MMM crew captures the moment.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/landscape/11.webp",
        alt: "Dancers from the Dancing With the Stars tour seated at a booth in a Panera restaurant the MMM crew captures the moment.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/landscape/12.webp",
        alt: "The MMM team photographers one of the dancers seated at a booth enjoying his lunch at a Panera restaurant.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/smith-saint/landscape/13.webp",
        alt: "A member of the MMM team holds a boom microphone over a group of dancers from the Dancing With the Stars tour seated in a booth at a Panera restaurant while they enjoy their meal.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
    ],
    videos: [
      {
        category: [
          "Corporate",
          "Video Editing",
          "Video Production",
          "Case Study",
          "Social Media",
        ],
        client: "Smith & Saint Talent Agency",
        description: "A 60-second commercial social media video promoting Panera's Mix & Match menu featuring dancers from the Dancing With the Stars tour.",
        mux_title: "smith-saint-panera",
        title: "Mix and Match with the Stars",
        image_src:
          "https://image.mux.com/NPVK80292isMIo2n5x02j00u3u00pprN3Azi5aaqxO5YWx00/thumbnail.webp?width=1080&height=1920&time=46",
        featured: "",
        slug: "smith-saint-panera",
        playback_id: "NPVK80292isMIo2n5x02j00u3u00pprN3Azi5aaqxO5YWx00",
        orientation: "vertical",
      },
    ],
  },
  {
    slug: "siteman-cancer-center",
    client: "Siteman Cancer Center",
    title: "Mammography Van Patient Education",
    short_title: "Mammography Van Education",
    campaign: "Mammography Van - What to Expect",
    short_campaign: "What to Expect",
    format: "Patient education video and marketing photography",
    short_format: "Educational Video & Photography",
    challenge: [
      "Nearly a decade after producing the original patient education video for Siteman Cancer Center's Mammography Van, the organization updated the vehicle with a new exterior wrap and refreshed branding. The team wanted to update their “What to Expect” video to reflect the new look while also capturing updated photography for marketing and outreach materials.",
      "The goal was to create a modernized video that would help patients feel comfortable and informed before visiting the mobile screening unit, while maintaining the trusted tone and messaging established in the original video.",
    ],
    approach: [
      "Mike Martin Media partnered with Siteman Cancer Center to produce an updated healthcare patient education video featuring new footage of the Mammography Van, drone videography to showcase the mobile unit in context, refreshed graphics, and an updated voice-over.",
      "Because MMM had produced the original video and worked with Siteman on numerous projects over the years, our team was able to quickly align with the organization's brand guidelines and messaging.",
      "We also leveraged archived footage from previous productions, allowing the updated video to build on existing visuals while incorporating new footage that reflects the van's current design and patient experience.",
    ],
    result: [
      "The updated Mammography Van patient education video provides patients with a clear and welcoming overview of what to expect during their visit, while supporting Siteman's ongoing outreach and early detection efforts.",
      "Alongside the video, new still photography captured during the shoot provided updated marketing assets for digital and print materials.",
    ],
    partnership: {
      type: "long-term",
      text: [
        "Mike Martin Media has enjoyed a long-standing partnership with Siteman Cancer Center, collaborating on projects that help communicate important healthcare information to patients and the community.",
        "Because our team understands Siteman's brand and maintains a library of archived footage from past productions, we're able to efficiently update and refresh content when needs evolve.",
        "We're grateful for the trust Siteman places in our team and proud to support their mission of improving cancer prevention, detection, and care.",
      ],
    },
    preview_image: {
      alt: "",
      url: "/images/case-studies/preview-images/siteman.png",
      width: 576,
      height: 324,
    },
    banner_images: [
      {
        url: "/images/case-studies/siteman-cancer-center/banner-images/0.png",
        alt: "The pink Siteman Cancer Center Mammogram Van parked in a parking lot.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/banner-images/1.png",
        alt: "The pink Siteman Cancer Center Mammogram Van parked in a parking lot, while the MMM crew pilots a drone to capture aerial footage and everyone gets ready for the shoot.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/banner-images/2.png",
        alt: "A healthcare worker welcomes a patient as they walk up the steps into the pink Siteman Cancer Center Mammogram Van.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/banner-images/3.png",
        alt: "A patient fills out intake paperwork at a desk inside the pink Siteman Cancer Center Mammogram Van with the assistance of a healthcare worker while the MMM crew captures the moment.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/banner-images/4.png",
         alt: "The pink Siteman Cancer Center Mammogram Van parked in a parking lot, while the MMM crew pilots a drone to capture aerial footage and everyone gets ready for the shoot.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/banner-images/5.png",
        alt: "A healthcare worker in conversation with a patient while they sit on a bench in the Mammogram Van.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/banner-images/6.png",
        alt: "The pink Siteman Cancer Center Mammogram Van parked in a parking lot, while an MMM drone captures aerial footage.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/banner-images/7.png",
        alt: "A patient fills out intake paperwork at a desk inside the Siteman Cancer Center Mammogram Van with the assistance of a healthcare worker.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/banner-images/8.png",
        alt: "The pink Siteman Cancer Center Mammogram Van parked in a parking lot, while the MMM crew pilots a drone to capture aerial footage and everyone gets ready for the shoot.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/banner-images/9.png",
        alt: "The pink Siteman Cancer Center Mammogram Van parked in a parking lot, while the MMM crew pilots a drone to capture aerial footage and everyone gets ready for the shoot.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/banner-images/10.png",
        alt: "The pink Siteman Cancer Center Mammogram Van parked in a parking lot, while the MMM crew pilots a drone to capture aerial footage and everyone gets ready for the shoot.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/banner-images/11.png",
        alt: "The pink Siteman Cancer Center Mammogram Van parked in a parking lot, while the MMM crew pilots a drone to capture aerial footage and everyone gets ready for the shoot.",
        width: 1728,
        height: 728,
        orientation: "landscape",
      },
    ],
    landscape_images: [
      {
        url: "/images/case-studies/siteman-cancer-center/landscape/0.webp",
        alt: "The pink Siteman Cancer Center Mammogram Van parked in a parking lot, while the MMM crew pilots a drone to capture aerial footage and everyone gets ready for the shoot.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/landscape/1.webp",
        alt: "A healthcare worker cares for a patient",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/landscape/2.webp",
        alt: "The pink Siteman Cancer Center Mammogram Van parked in a parking lot, while the MMM crew pilots a drone to capture aerial footage and everyone gets ready for the shoot.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/landscape/3.webp",
        alt: "A healthcare worker reviews MRI images on a screen.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/landscape/4.webp",
        alt: "The pink Siteman Cancer Center Mammogram Van parked in a parking lot, while the MMM crew pilots a drone to capture aerial footage and everyone gets ready for the shoot.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/landscape/5.webp",
        alt: "A patient fills out intake paperwork at a desk inside the Siteman Cancer Center Mammogram Van with the assistance of a healthcare worker.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/landscape/6.webp",
        alt: "The pink Siteman Cancer Center Mammogram Van parked in a parking lot, while the MMM crew pilots a drone to capture aerial footage and everyone gets ready for the shoot.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/landscape/7.webp",
        alt: "A healthcare worker cares for a patient at the Siteman Cancer Center",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/landscape/8.webp",
        alt: "The pink Siteman Cancer Center Mammogram Van parked in a parking lot, while an MMM drone captures aerial footage.",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
      {
        url: "/images/case-studies/siteman-cancer-center/landscape/9.webp",
        alt: "A healthcare worker assists a patient with a medical procedure at the Siteman Cancer Center",
        width: 1920,
        height: 1080,
        orientation: "landscape",
      },
    ],
    portrait_images: [
      {
        url: "/images/case-studies/siteman-cancer-center/portrait/7.webp",
        alt: "A patient fills out intake paperwork at a desk inside the Siteman Cancer Center Mammogram Van with the assistance of a healthcare worker while the MMM crew captures the moment.",
        width: 1080,
        height: 1920,
        orientation: "portrait",
      },
    ],
    videos: [
      {
        category: [
          "Medical",
          "Video Editing",
          "Video Production",
          "Case Study",
        ],
        client: "Siteman Cancer Center",
        description:
          "The updated Mammography Van patient education video provides patients with a clear and welcoming overview of what to expect during their visit, while supporting Siteman's ongoing outreach and early detection efforts.",
        mux_title: "siteman-cancer-center",
        title: "Siteman Cancer Center - Mammography Van",
        image_src:
          "https://image.mux.com/Hwh01HHmGfBtLqlOwGyyVjS01yJtpFETmFMjtigAo3i38/thumbnail.webp?width=1920&height=1080&time=03",
        featured: "",
        slug: "siteman-cancer-center",
        playback_id: "Hwh01HHmGfBtLqlOwGyyVjS01yJtpFETmFMjtigAo3i38",
        orientation: "horizontal",
      },
    ],
  },
  // {
  //   client: "",
  //   title: "",
  //   short_title: "",
  //   campaign: "",
  //   short_campaign: "",
  //   format: "",
  //   challenge: [],
  //   approach: [],
  //   result: [],
  //   preview_image: {
  //     alt: "",
  //     url: "",
  //     width: 1080,
  //     height: 1080,
  //   },
  //   videos: [
  //     {
  //       id: "",
  //     },
  //   ],
  // },
];
